---
- name: Set timezone to Europe/Moscow
  timezone:
    hwclock: 'UTC'
    name: Europe/Moscow
  become: yes

- name: Check is ntp enabled
  shell: timedatectl | grep "System clock synchronized\|NTP synchronized" | awk '{ print $NF }'
  register: reg_timedatectl_ntp
  changed_when: false

- name: Copy ntp config file
  copy:
    src: timesyncd.conf
    dest: /etc/systemd/timesyncd.conf
    mode: '0446'
    group: root
    owner: root
  become: yes

- name: Enable ntp
  command: timedatectl set-ntp true
  when: reg_timedatectl_ntp.stdout != 'yes'
  become: yes
