---
- name: Set timezone to Europe/Moscow
  community.general.timezone:
    hwclock: UTC
    name: Europe/Moscow
  become: true

- name: Check is ntp enabled
  ansible.builtin.shell: timedatectl | grep "System clock synchronized\|NTP synchronized" | awk '{ print $NF }'
  register: reg_timedatectl_ntp
  changed_when: false

- name: Copy ntp config file
  ansible.builtin.copy:
    src: timesyncd.conf
    dest: /etc/systemd/timesyncd.conf
    group: root
    owner: root
    mode: "0446"
  become: true

- name: Enable ntp
  ansible.builtin.command: timedatectl set-ntp true
  when: reg_timedatectl_ntp.stdout != 'yes'
  become: true
