---
reangd_repositories_map:
  - { repo: "ansible-personal.git",           dest: "ansible-personal" }
  - { repo: "bot-platform.git",               dest: "bot-platform" }
  - { repo: "cpp-coroutine.git",              dest: "cpp-coroutine" }
  - { repo: "cpp-network.git",                dest: "cpp-network" }
  - { repo: "cpp-rtge.git",                   dest: "cpp-rtge" }
  - { repo: "vscode-devdocs-io.git",          dest: "vscode-devdocs-io" }
  - { repo: "docker-alpine.git",              dest: "docker-alpine" }
  - { repo: "dokuwiki-plugin-addnewpage.git", dest: "dokuwiki-plugin-addnewpage" }
  - { repo: "dokuwiki-tablecalc.git",         dest: "dokuwiki-tablecalc" }
  - { repo: "dotfiles.git",                   dest: "dotfiles" }
  - { repo: "dotfiles-hass.git",              dest: "dotfiles-hass" }
  - { repo: "dotfiles-jetbrains.git",         dest: "dotfiles-jetbrains" }
  - { repo: "dotfiles-pycharm.git",           dest: "dotfiles-pycharm" }
  - { repo: "emacs-multi-compile.git",        dest: "emacs-multi-compile" }
  - { repo: "evolution.git",                  dest: "evolution" }
  - { repo: "go-algo.git",                    dest: "go/src/github.com/ReanGD/go-algo" }
  - { repo: "go-morphy.git",                  dest: "go/src/github.com/ReanGD/go-morphy" }
  - { repo: "go-web-search.git",              dest: "go/src/github.com/ReanGD/go-web-search" }
  - { repo: "HabrArticle.git",                dest: "HabrArticle" }
  - { repo: "LearningEnglish.git",            dest: "LearningEnglish" }
  - { repo: "neural-network.git",             dest: "neural-network" }
  - { repo: "py-calendar.git",                dest: "py-calendar" }
  - { repo: "py-invest.git",                  dest: "py-invest" }
  - { repo: "reangd.github.io.git",           dest: "reangd.github.io" }
  - { repo: "rofi-proxy",                     dest: "rofi-proxy" }
  - { repo: "rust-open3d.git",                dest: "rust-open3d" }
  - { repo: "rust-software-render.git",       dest: "rust-software-render" }
  - { repo: "SimpleLang.git",                 dest: "SimpleLang" }
  - { repo: "smart-home.git",                 dest: "smart-home" }
  - { repo: "sublime-powerslim.git",          dest: "sublime-powerslim" }
  - { repo: "web-home-manage.git",            dest: "web-home-manage" }
  - { repo: "zrpc.git",                       dest: "zrpc" }

terra_repositories_map:
  - { repo: "TerraEngine.git", dest: "TerraEngine" }
