---
- name: Install rsync package
  pkg_manager:
    name: rsync
  become: yes
  become_user: "{{ install_user }}"

- name: Enable rsyncd service
  service:
    name: rsyncd.service
    enabled: yes
  become: yes
