---
- name: Update local mashine
  hosts: local
  gather_facts: false
  environment:
    GNUPGHOME: /home/rean/.config/gnupg
  pre_tasks:
    - include: common/tasks/init_facts.yml is_chroot_param=False
  roles:
    - locale
    - users
    - network
    - packages_manager
    # update required for each machine
    - ssh
    - role: boot
      when: x86_64
    - swap
    - systemd_configure
    - time
    - role: font
      when: "'font' in roles.split(',')"
    - role: pkgcacheclean
      when: x86_64
    - role: docker
      when: "'docker' in roles.split(',')"
    - role: automount
      when: "'automount' in roles.split(',')"
    - role: monitoring
      when: "monitoring!='none'"
    - role: repository
      when: "'repository' in roles.split(',')"
    - role: dotfiles
      when: "'dotfiles' in roles.split(',')"
    # update required for each machine
    - role: gui
      when: "gui!='none'"
    - role: virtualization
      when: "virtualization!='none'"
    - role: vs_code
      when: "develop!='none'"
    - packages
    - clear
