---
- name: Copy settings from home assistant to local host
  hosts: hass
  gather_facts: false
  pre_tasks:
    - include: common/tasks/init_facts.yml is_chroot_param=False
  roles:
    - hass_update
