---
- name: Copy settings from home assistant to local host
  hosts: hass
  gather_facts: false
  pre_tasks:
    - import_tasks: tasks/common/init_facts.yml
      vars:
        is_chroot_param: False
  roles:
    - hass_copy
