---
- name: Update home assistant
  hosts: hass
  gather_facts: false
  pre_tasks:
    - import_tasks: common/tasks/init_facts.yml
      vars:
        is_chroot_param: False
  roles:
    - hass_update
