---
- name: Base install home assistant
  hosts: hass
  gather_facts: false
  pre_tasks:
    - import_tasks: common/tasks/init_facts.yml
      vars:
        is_chroot_param: False
  roles:
    - locale
    - users
    - network
    - packages_manager
    - ssh
    - swap
    - systemd_configure
    - time
    - role: monitoring
      when: monitoring!="none"
    - rsync_server
    - mosquitto
    - packages
    - hass_ssl
    - hass_server
    - hass_update
