---
- name: Base install home assistant
  hosts: hass
  gather_facts: false
  pre_tasks:
    - include: common/tasks/init_facts.yml is_chroot_param=False
  roles:
    - locale
    - users
    - network
    - packages_manager
    - ssh
    - swap
    - systemd_configure
    - time
    - hddtemp
    - rsync_server
    - mosquitto
    - hass_ssl
    - hass_server
    - packages
    - hass_update
