---
- name: Get info about "{{ variable_host }}"
  hosts: "{{ variable_host }}"
  gather_facts: false
  pre_tasks:
    - include: common/tasks/init_facts.yml is_chroot_param=False
  roles:
    - get_info
