---
- name: Get info about "{{ variable_host }}"
  hosts: "{{ variable_host }}"
  gather_facts: false
  pre_tasks:
    - import_tasks: tasks/common/init_facts.yml
      vars:
        is_chroot_param: False
  roles:
    - get_info
