---
- name: Test playbook
  hosts: server
  gather_facts: false
  environment:
    GNUPGHOME: /home/rean/.config/gnupg
    KUBECONFIG: /etc/rancher/k3s/k3s.yaml
  pre_tasks:
    - import_tasks: common/tasks/init_facts.yml
      vars:
        is_chroot_param: False
  roles:
    - k8s_charts
