---
- name: Update local mashine
  hosts: local
  connection: local
  gather_facts: false
  pre_tasks:
    - include: common/init_facts.yml is_chroot_param=False
  roles:
    - locale
    - users
    - network
    - packages_manager
    - boot
