---
- hosts: localhost

  vars:
    ansible_connection: local
    ansible_python_interpreter: /usr/bin/python2
    main_user: rean
    # python2 -c 'import crypt; print crypt.crypt("This is my Password", "$1$SomeSalt$")'
    password: Xa9ABykCX7ocU
    gopath: "{{lookup('env','GOPATH_BASE')}}"

  vars_files:
    - vars/dotfiles_map.yml
    - vars/repository_map.yml

  tasks:
    - include: tasks/pacman.yml
    - include: tasks/user.yml
    - include: tasks/common/systemd.yml
    - include: tasks/services.yml
    - include: tasks/sudo.yml
    - include: tasks/yaourt.yml
    - include: tasks/git.yml
    - include: tasks/packages.yml
    - include: tasks/systemd_after.yml
    - include: tasks/dotfiles.yml
    - include: tasks/firefox.yml
    - include: tasks/repository.yml
    - include: tasks/xorg.yml
    - include: tasks/autofs.yml
    - include: tasks/remove_cfg.yml
    - include: tasks/go.yml
