---
- hosts: localhost

  vars:
    ansible_connection: local
    ansible_python_interpreter: /usr/bin/python2
  
  environment:
    GNUPGHOME: /home/rean/.config/gnupg

  vars_files:
    - vars/common.yml
    - vars/dotfiles_map.yml
    - vars/repository_map.yml

  tasks:
    - include: tasks/common/init.yml
    - include: tasks/common/locale.yml
    - include: tasks/common/pacman.yml
    - include: tasks/common/user.yml
    - include: tasks/common/grub.yml
    # after root
    - include: tasks/packages.yml
    - include: tasks/common/time.yml
    - include: tasks/common/systemd.yml
    - include: tasks/services.yml
    - include: tasks/git.yml
    - include: tasks/gpg.yml
    - include: tasks/systemd_after.yml
    - include: tasks/dotfiles.yml
    - include: tasks/repository.yml
    - include: tasks/xorg.yml
    - include: tasks/common/autofs.yml
    - include: tasks/remove_cfg.yml
    # after packages
    - include: tasks/monitoring.yml
    - include: tasks/go.yml
