---
- hosts: localhost

  vars:
    ansible_connection: local
    ansible_python_interpreter: /usr/bin/python2
    user: rean

  vars_files:
    - vars/dotfiles_map.yml

  tasks:
    - include: tasks/pacman.yml
    - include: tasks/sudo.yml
    - include: tasks/aur.yml
    - include: tasks/git.yml
    - include: tasks/packages.yml
    - include: tasks/dotfiles.yml
    - include: tasks/rust.yml
    - include: tasks/remove_cfg.yml
