---
- name: Install local mashine
  hosts: local
  gather_facts: false
  environment:
    GNUPGHOME: /home/rean/.config/gnupg
  pre_tasks:
    - include: common/tasks/init_facts.yml is_chroot_param=True
  roles:
    - locale
    - users
    - network
    - packages_manager
    - role: setup
      when: is_chroot == True
    - ssh
    - role: boot
      when: x86_64
    - swap
    - systemd_configure
