---
- name: Setup "{{ variable_host }}"
  hosts: "{{ variable_host }}"
  gather_facts: false
  environment:
    GNUPGHOME: /home/rean/.config/gnupg
  pre_tasks:
    - import_tasks: tasks/common/init_facts.yml
  roles:
    - locale
    - users
    - network
    - sudo
    - packages_manager
    - role: setup
      when: is_chroot and x86_64
    - ssh
    - role: boot
      when: x86_64
    - swap
    - systemd_configure
    - role: time
      when: not is_chroot
    - role: font
      when: '"font" in roles.split(",")'
    - role: audio
      when: '"audio" in roles.split(",")'
    - role: docker
      when: '"docker" in roles.split(",")'
    - role: automount
      when: '"automount" in roles.split(",")'
    - role: rsync_server
      when: '"rsync_server" in roles.split(",")'
    - role: sing_box
      when: 'not is_chroot and "sing_box" in roles.split(",")'
    - role: hass
      when: '"hass" in roles.split(",")'
    - role: hass_maintenance
      var:
        is_hass_copy: False
        is_hass_update: True
      when: '"hass" in roles.split(",")'
    - role: monitoring
      when: monitoring!="none"
    - role: packages
      when: not is_chroot
    - role: pkgcacheclean
      when: x86_64
    - role: repository
      when: 'not is_chroot and "repository" in roles.split(",")'
    - role: dotfiles
      when: not is_chroot and x86_64
    - role: nix
      when: '"nix" in roles.split(",")'
    - role: gui
      when: not is_chroot and gui!="none"
    - role: vs_code
      when: not is_chroot and develop!="none"
    - clear
