---
- name: Test playbook
  # hosts: server
  hosts: local
  gather_facts: false
  environment:
    GNUPGHOME: /home/rean/.config/gnupg
  pre_tasks:
    - import_tasks: common/tasks/init_facts.yml
      vars:
        is_chroot_param: False
  roles:
    - test
