---
- name: Test playbook
  # hosts: server
  hosts: local
  gather_facts: false
  environment:
    GNUPGHOME: /home/rean/.config/gnupg
  pre_tasks:
    - include: common/tasks/init_facts.yml is_chroot_param=False
  roles:
    - test
