---
- name: Create config dir
  ansible.builtin.file:
    path: /etc/3proxy
    state: directory
    group: proxy3
    owner: "{{ main_user }}"
    mode: "0550"
  become: true

- name: Fill and copy config
  ansible.builtin.template:
    src: 3proxy-cfg.j2
    dest: /etc/3proxy/3proxy.cfg
    group: proxy3
    owner: "{{ main_user }}"
    mode: "0440"
  become: true

# ansible-vault decrypt
# ansible-vault encrypt
- name: Create auth config
  ansible.builtin.copy:
    src: auth
    dest: /etc/3proxy/auth
    group: proxy3
    owner: proxy3
    mode: "0440"
  become: true
