---
- import_tasks: arch_pkg.yml
  when: distro == "arch" or distro == "archarm"

- import_tasks: debian_pkg.yml
  when: distro == "debian"

- import_tasks: user.yml

- name: Stop service
  ansible.builtin.service:
    name: 3proxy.service
    state: stopped
  become: true
  when: "proxy3_reinstall"

- name: Check that binary exists
  ansible.builtin.stat:
    path: /usr/bin/3proxy
    get_checksum: false
    get_mime: false
  register: reg_3proxy_bin_exists
  become: true

- import_tasks: bin.yml
  when: "proxy3_reinstall or not reg_3proxy_bin_exists.stat.exists"

- import_tasks: config.yml

- name: Check that log dir exists
  ansible.builtin.stat:
    path: /var/log/3proxy
    get_checksum: false
    get_mime: false
  register: reg_3proxy_log_exists
  become: true

- import_tasks: log.yml
  when: "proxy3_reinstall or not reg_3proxy_log_exists.stat.exists"

- import_tasks: systemd.yml
- import_tasks: ufw.yml
