---
- name: Create gpg dir
  file:
    path: "/home/{{ main_user }}/.config/gnupg"
    state: directory
    mode: 0700
    group: users
    owner: "{{ main_user }}"

- name: Install package gnupg
  pkg_manager:
    name: gnupg
  become: true
  become_user: "{{ install_user }}"

- name: Import package keys
  pkg_manager:
    command: import_config_keys
    config: "{{ packages_file }}"
  become: true

- name: Install packages
  pkg_manager:
    command: install_config
    config: "{{ packages_file }}"
  become: true
  become_user: "{{ install_user }}"
