---
- name: Create gpg dir
  ansible.builtin.file:
    path: "/home/{{ main_user }}/.config/gnupg"
    state: directory
    group: users
    owner: "{{ main_user }}"
    mode: "0700"
  become: true

- name: Install package gnupg
  pkg_manager:
    name: gnupg
    command: install
  become: true
  become_user: "{{ install_user }}"

- name: Import package keys
  pkg_manager:
    config: "{{ packages_file }}"
    command: import_config_keys
  become: true

- name: Install packages
  pkg_manager:
    config: "{{ packages_file }}"
    command: install_config
  become: true
  become_user: "{{ install_user }}"
