---
- name: Create gpg dir
  file:
    path: "/home/{{main_user}}/.config/gnupg"
    state: directory
    mode: 0700
    group: users
    owner: "{{main_user}}"

- name: Install package gnupg
  pkg_manager:
    name: gnupg

# - name: Add key for tor-browser-ru
#   command: pacman-key --recv-keys 0x4E2C6E8793298290
#   changed_when: false
#   when: hostname_id in ["archhost", "archnote"]
#   become: yes

- name: Install packages
  pkg_manager:
    command: install_config
    config: "{{packages_file}}"
