---
- name: Install package refind-efi
  pkg_manager:
    name: refind-efi

- name: Check that the /boot/efi/EFI exists
  stat:
    path: /boot/efi/EFI
    get_checksum: no
    get_mime: no
  register: reg_efi_installed
  become: yes

- name: Find efi partition name
  shell: findmnt -o SOURCE --noheadings /boot/efi
  register: efi_partition_name_reg
  changed_when: false

- name: Find root partition uuid
  shell: findmnt -o UUID --noheadings /
  register: root_partition_uuid_reg
  changed_when: false

- name: Set partitions facts
  set_fact:
    efi_partition_name: "{{ efi_partition_name_reg.stdout }}"
    root_partition_uuid: "{{ root_partition_uuid_reg.stdout }}"
    conf_path: "{% if boot_ssd == True %}/boot/efi/EFI/BOOT/refind.conf{% else %}/boot/efi/EFI/refind/refind.conf{% endif %}"

- name: UEFI install to SSD
  shell: refind-install --usedefault {{ efi_partition_name }} --alldrivers
  when: boot_ssd == True and reg_efi_installed.stat.exists == False
  become: yes

- name: UEFI install to HDD
  shell: refind-install
  when: boot_ssd == False and reg_efi_installed.stat.exists == False
  become: yes

- name: Create refind_linux config
  template:
    src: refind_linux.conf
    dest: /boot/refind_linux.conf
    mode: 0644
    owner: root
    group: root
  become: yes

- name: Update refind timeout
  lineinfile:
    regexp: "^timeout .*$"
    line: "timeout 1"
    path: "{{conf_path}}"
  become: yes
