---
- name: Check swapfile
  stat:
    path: /swapfile
    get_checksum: no
    get_mime: no
  register: reg_swapfile
  become: yes

- name: Create swapfile
  command: dd if=/dev/zero of=/swapfile bs=1G count={{ swap_size }}
  become: yes
  when: not reg_swapfile.stat.exists

- name: Set swapfile permissions
  file:
    path: /swapfile
    mode: 0600
    group: root
    owner: root
  become: yes

- name: Init swapfile
  command: mkswap /swapfile
  become: yes
  when: not reg_swapfile.stat.exists

- name: Enable swapfile
  command: swapon /swapfile
  become: yes
  when: not reg_swapfile.stat.exists

- name: Add swapfile to /etc/fstab
  lineinfile:
    dest: /etc/fstab
    line: "/swapfile none swap defaults 0 0"
    state: present
  become: yes
  when: not reg_swapfile.stat.exists

- name: Configure swap settings
  template:
    src: 99-sysctl.conf
    dest: /etc/sysctl.d/99-sysctl.conf
    mode: 0644
    group: root
    owner: root
  become: yes
