---
- name: Check swapfile
  stat:
    path: /swapfile
    get_checksum: no
    get_mime: no
  register: reg_swapfile
  become: true

- name: Create swapfile
  ansible.builtin.command: dd if=/dev/zero of=/swapfile bs=1M count={{ swap_size }}
  become: true
  when: not reg_swapfile.stat.exists

- name: Set swapfile permissions
  file:
    path: /swapfile
    group: root
    owner: root
    mode: "0600"
  become: true

- name: Init swapfile
  ansible.builtin.command: mkswap /swapfile
  become: true
  when: not reg_swapfile.stat.exists

- name: Enable swapfile
  ansible.builtin.command: swapon /swapfile
  become: true
  when: not reg_swapfile.stat.exists

- name: Add swapfile to /etc/fstab
  lineinfile:
    dest: /etc/fstab
    line: "/swapfile none swap defaults 0 0"
    state: present
  become: true
  when: not reg_swapfile.stat.exists

- name: Configure swap settings
  ansible.builtin.template:
    src: 99-sysctl.conf
    dest: /etc/sysctl.d/99-sysctl.conf
    group: root
    owner: root
    mode: "0644"
  become: true
