---
- name: Check git repo
  command: git -C ~/projects/git/dotfiles/ status --porcelain
  changed_when: false
  register: output

- name: Clone dotfiles repo
  git: repo=git@github.com:ReanGD/dotfiles.git dest=~/projects/git/dotfiles/
  when: output.stdout == "" and output.stderr == ""

- name: Create links for dotfiles
  link: src=~/projects/git/dotfiles/{{item.src}} dst={{item.dst}}
  with_items: dotfiles_path_map

- name: Create links for documents
  link: src={{item.src}} dst={{item.dst}}
  with_items: documents_path_map
