---
- name: Create cfg dirs
  file: path={{item}} state=directory mode=0755
  with_items:
    - ~/.config/pulse
    - ~/cloud/Dropbox
    - ~/tmp
    - ~/downloads
    - ~/doc
    - ~/.cache

- name: Create links for dotfiles
  link: src=~/projects/git/dotfiles/{{item.src}} dst={{item.dst}}
  with_items: "{{ dotfiles_path_map }}"

- name: Create links for documents
  link: src={{item.src}} dst={{item.dst}}
  with_items: "{{ documents_path_map }}"
