--- # packages.yml + network.yml
- name: Install go utils without sudo
  command: go get -u {{item}}
  with_items:
    - 'github.com/nsf/gocode'
    - 'github.com/rogpeppe/godef'
    - 'github.com/jstemmer/gotags'
    - 'github.com/kisielk/errcheck'
    - 'golang.org/x/tools/cmd/guru'
    - 'github.com/golang/lint/golint'
    - 'golang.org/x/tools/cmd/gorename'
    - 'golang.org/x/tools/cmd/goimports'
  tags:
    - update

- name: Install go utils with sudo
  command: go get -u {{item}}
  become: yes
  with_items:
    - 'golang.org/x/tools/cmd/godoc'
  tags:
    - update
