---
- name: Install godef
  command: go get github.com/rogpeppe/godef creates={{gopath}}/bin/godef

- name: Install gocode
  command: go get github.com/nsf/gocode creates={{gopath}}/bin/gocode

- name: Install golint
  command: go get github.com/golang/lint/golint creates={{gopath}}/bin/golint

- name: Install errcheck
  command: go get github.com/kisielk/errcheck creates={{gopath}}/bin/errcheck

- name: Install goimports
  command: go get golang.org/x/tools/cmd/goimports creates={{gopath}}/bin/goimports

- name: Update go utils
  command: "{{item}}"
  with_items:
    - go get -u github.com/rogpeppe/godef
    - go clean -i github.com/rogpeppe/godef
    - go install -v github.com/rogpeppe/godef
    - go get -u github.com/nsf/gocode
    - go clean -i github.com/nsf/gocode
    - go install -v github.com/nsf/gocode
    - go get -u github.com/golang/lint/golint
    - go clean -i github.com/golang/lint/golint
    - go install -v github.com/golang/lint/golint
    - go get -u github.com/kisielk/errcheck
    - go clean -i github.com/kisielk/errcheck
    - go install -v github.com/kisielk/errcheck
    - go get -u golang.org/x/tools/cmd/goimports
    - go clean -i golang.org/x/tools/cmd/goimports
    - go install -v golang.org/x/tools/cmd/goimports
  tags:
    - update
