---
- name: Install go utils
  command: go get {{item.url}} creates={{gopath}}/bin/{{item.name}}
  with_items:
    - { url: 'github.com/rogpeppe/godef', name: 'godef' }
    - { url: 'github.com/nsf/gocode', name: 'gocode' }
    - { url: 'github.com/golang/lint/golint', name: 'golint' }
    - { url: 'github.com/kisielk/errcheck', name: 'errcheck' }
    - { url: 'golang.org/x/tools/cmd/goimports', name: 'goimports' }
    - { url: 'golang.org/x/tools/cmd/oracle', name: 'oracle' }
    - { url: 'golang.org/x/tools/cmd/gorename', name: 'gorename' }

- name: Update go utils
  command: "{{item}}"
  with_items:
    - go get -u github.com/rogpeppe/godef
    - go clean -i github.com/rogpeppe/godef
    - go install -v github.com/rogpeppe/godef
    - go get -u github.com/nsf/gocode
    - go clean -i github.com/nsf/gocode
    - go install -v github.com/nsf/gocode
    - go get -u github.com/golang/lint/golint
    - go clean -i github.com/golang/lint/golint
    - go install -v github.com/golang/lint/golint
    - go get -u github.com/kisielk/errcheck
    - go clean -i github.com/kisielk/errcheck
    - go install -v github.com/kisielk/errcheck
    - go get -u golang.org/x/tools/cmd/goimports
    - go clean -i golang.org/x/tools/cmd/goimports
    - go install -v golang.org/x/tools/cmd/goimports
    - go get -u golang.org/x/tools/cmd/oracle
    - go clean -i golang.org/x/tools/cmd/oracle
    - go install -v golang.org/x/tools/cmd/oracle
    - go get -u golang.org/x/tools/cmd/gorename
    - go clean -i golang.org/x/tools/cmd/gorename
    - go install -v golang.org/x/tools/cmd/gorename
  tags:
    - update
