--- # init.yml + network.yml
- name: Refresh package list
  yaourt: update_cache=yes
  changed_when: false

- name: Create gpg dir
  file: path=~/.config/gnupg state=directory mode=700

- name: Install package gnupg
  pacman: name=gnupg state=present
  become: yes

- name: Add key for tor-browser-ru
  command: gpg --keyserver hkp://pgp.mit.edu:11371 --recv-keys 0x4E2C6E8793298290
  changed_when: false

- name: Install packages
  yaourt: name={{ item }} state=present
  with_cfg_file: vars/packages.py action=not_installed host={{hostname_id}}

- name: Get new packages
  shell: echo "{{ item }}"
  with_cfg_file: vars/packages.py action=new host={{hostname_id}}
  tags: view_new

- name: Get error packages
  shell: echo "{{ item }}"
  with_cfg_file: vars/packages.py action=error host={{hostname_id}}
  tags: view_new
