---
- name: Remove bash config
  file: path={{ item }} state=absent
  with_items:
    - ~/.bash_history
    - ~/.bash_logout
    - ~/.bash_profile
    - ~/.bashrc

- name: Remove gnupg config
  file: path=~/.gnupg state=absent
  become: yes

- name: Remove nv config
  file: path=~/.nv state=absent
  become: yes
