---
- name: Create cfg dirs
  ansible.builtin.file:
    path: "/home/{{ main_user }}/{{ item }}"
    state: directory
    group: users
    owner: "{{ main_user }}"
    mode: "0755"
  become: true
  loop:
    - cloud
    - doc

- name: Create links for documents
  link:
    src: "/home/{{ main_user }}/cloud/Dropbox/{{ item.src }}"
    dst: "/home/{{ main_user }}/{{ item.dst }}"
  loop: "{{ documents_path_map }}"
