---

- name: Install packages for parse doublecmd configs
  pkg_manager:
    name: python-lxml
    command: install
  become: true
  become_user: "{{ install_user }}"

- name: Check that the doublecmd config exists
  ansible.builtin.stat:
    path: "/home/{{ main_user }}/.config/doublecmd/doublecmd.xml"
    get_checksum: false
    get_mime: false
  register: reg_doublecmd_cfg_exists

- name: Backup doublecmd config
  ansible.builtin.copy:
    src: "/home/{{ main_user }}/.config/doublecmd/doublecmd.xml"
    dest: "/home/{{ main_user }}/.config/doublecmd/doublecmd.xml.backup"
    group: users
    owner: "{{ main_user }}"
    mode: "0644"
  when: reg_doublecmd_cfg_exists.stat.exists
  changed_when: false
  become: true

- name: Remove from doublecmd config backup unused elements
  community.general.xml:
    path: "/home/{{ main_user }}/.config/doublecmd/doublecmd.xml.backup"
    xpath: "{{ item }}"
    state: absent
    pretty_print: true
  loop:
    - "/doublecmd/Tabs/*"
    - "/doublecmd/Icons/*"
    - "/doublecmd/MainWindow/*"
    - "/doublecmd/ColumnsSets/*"
  when: reg_doublecmd_cfg_exists.stat.exists
  changed_when: false

- name: Copy doublecmd config from backup
  ansible.builtin.copy:
    src: "/home/{{ main_user }}/.config/doublecmd/doublecmd.xml.backup"
    dest: "/home/{{ main_user }}/.config/doublecmd/doublecmd.xml"
    group: users
    owner: "{{ main_user }}"
    mode: "0644"
  when: not reg_doublecmd_cfg_exists.stat.exists
  become: true
