---
- name: Create cfg dirs
  file:
    path: "/home/{{main_user}}/{{item}}"
    state: directory
    mode: 0755
    group: users
    owner: "{{main_user}}"
  loop:
    - .config/Code/User
    - .config/pulse
    - cloud
    - tmp
    - downloads
    - doc
    - .cache
    - projects/test
    - projects/work
    - projects/external
    - projects/venv

- name: Create links for dotfiles
  link:
    src: /home/{{main_user}}/projects/home/dotfiles/{{item.src}}
    dst: /home/{{main_user}}/{{item.dst}}
  loop: "{{ dotfiles_path_map }}"

- name: Create links for documents
  link:
    src: "/home/{{main_user}}/cloud/Dropbox/{{item.src}}"
    dst: "/home/{{main_user}}/{{item.dst}}"
  loop: "{{ documents_path_map }}"
