---
- name: Copy uprofile.sh to /etc/profile.d
  ansible.builtin.copy:
    src: start_profile.sh
    dest: /etc/profile.d/start_profile.sh
    group: root
    owner: root
    mode: "0644"
  become: true

- name: Create cfg dirs
  ansible.builtin.file:
    path: "/home/{{ main_user }}/{{ item }}"
    state: directory
    group: users
    owner: "{{ main_user }}"
    mode: "0755"
  loop:
    - .local/share
    - .local/share/zsh
    - .local/share/rofi
    - .local/share/vscode
    - .local/share/applications
    - .local/share/firefox/.mozilla/firefox/rean.default-release
    - .cache
    - .cache/zsh
    - .config
    - .config/lib
    - .config/pulse
    - .config/Code/User
    - .config/autostart-scripts
    - .config/sublime-text-3/Packages/User/
    - tmp
    - downloads
    - projects/test
    - projects/work
    - projects/external
    - projects/venv
  become: true

- name: Clone or update dotfile repositories
  update_git:
    repo: git@github.com:ReanGD/{{ item.repo }}
    dest: /home/{{ main_user }}/projects/home/{{ item.dest }}
  loop: "{{ dotfiles_repositories_map }}"

- name: Create links for dotfiles
  link:
    src: /home/{{ main_user }}/projects/home/dotfiles/{{ item.src }}
    dst: /home/{{ main_user }}/{{ item.dst }}
  loop: "{{ dotfiles_path_map }}"

- name: Create links for GUI dotfiles
  link:
    src: /home/{{ main_user }}/projects/home/dotfiles/{{ item.src }}
    dst: /home/{{ main_user }}/{{ item.dst }}
  when: gui!="none"
  loop: "{{ dotfiles_gui_path_map }}"

- name: Create links for other items
  link:
    src: "{{ item.src }}"
    dst: /home/{{ main_user }}/{{ item.dst }}
  when: gui!="none"
  loop: "{{ others_path_map }}"

# ansible-vault decrypt secrets.yml
# ansible-vault encrypt secrets.yml
- name: Include vars git user configs
  include_vars:
    file: secrets.yml

- name: Create git user configs
  ansible.builtin.copy:
    content: "{{ item.key }}"
    dest: "/home/{{ main_user }}/.config/git/{{ item.name }}"
    group: users
    owner: "{{ main_user }}"
    mode: "0644"
  become: true
  loop:
    - { key: "{{ git_user_home }}", name: "user.home" }
    - { key: "{{ git_user_work }}", name: "user.work" }
  loop_control:
    label: "{{ item.name }}"

- name: Create set_hidden_params.sh
  ansible.builtin.template:
    src: set_hidden_params.sh
    dest: "/home/{{ main_user }}/.config/start/set_hidden_params.sh"
    group: users
    owner: "{{ main_user }}"
    mode: "0644"
  become: true

- import_tasks: cloud.yml
  when: gui!="none"

- import_tasks: doublecmd.yml
  when: gui!="none"

- name: Install packages for update desktop database
  pkg_manager:
    name: desktop-file-utils
    command: install
  when: gui!="none"
  become: true
  become_user: "{{ install_user }}"

- name: Update desktop database
  ansible.builtin.command: update-desktop-database ~/.local/share/applications
  when: gui!="none"
  changed_when: false
