---
- name: Copy uprofile.sh to /etc/profile.d
  copy:
    src: start_profile.sh
    dest: /etc/profile.d/start_profile.sh
    mode: 0644
    group: root
    owner: root
  become: yes

- name: Create cfg dirs
  file:
    path: "/home/{{main_user}}/{{item}}"
    state: directory
    mode: 0755
    group: users
    owner: "{{main_user}}"
  loop:
    - .local/share
    - .local/share/zsh
    - .cache
    - .cache/zsh
    - .config
    - .config/lib
    - .config/Code/User
    - .config/pulse
    - .config/sublime-text-3/Packages/User/
    - tmp
    - downloads
    - projects/test
    - projects/work
    - projects/external
    - projects/venv

- name: Clone or update dotfile repositories
  update_git:
    repo: git@github.com:ReanGD/{{item.repo}}
    dest: /home/{{main_user}}/projects/home/{{item.dest}}
  loop: "{{ dotfiles_repositories_map }}"

- name: Create links for dotfiles
  link:
    src: /home/{{main_user}}/projects/home/dotfiles/{{item.src}}
    dst: /home/{{main_user}}/{{item.dst}}
  loop: "{{ dotfiles_path_map }}"

- include: cloud.yml
  when: gui!="none"

- include: doublecmd.yml
  when: gui!="none"
