---
- name: Install package pkgcacheclean
  pkg_manager:
    name: pkgcacheclean
    command: install
  become: true
  become_user: "{{ install_user }}"

- name: Timer pkgcacheclean
  ansible.builtin.copy:
    src: pkgcacheclean.timer
    dest: /etc/systemd/system/pkgcacheclean.timer
    group: root
    owner: root
    mode: "0644"
  become: true

- name: Service pkgcacheclean
  ansible.builtin.copy:
    src: pkgcacheclean.service
    dest: /etc/systemd/system/pkgcacheclean.service
    group: root
    owner: root
    mode: "0644"
  become: true

- name: Enable pkgcacheclean service
  ansible.builtin.service:
    name: pkgcacheclean.timer
    enabled: true
  become: true
