---
# alternatives:
# xrandr --current --verbose | grep Brightness
# xrandr --output DP-0 --brightness 0.9

- name: Install package for brightness control
  pkg_manager:
    name: ddcutil
    command: install
  become: true
  become_user: "{{ install_user }}"

- name: Load kernel module for ddcutil
  ansible.builtin.copy:
    src: brightness.conf
    dest: /etc/modules-load.d/brightness.conf
    group: root
    owner: root
    mode: "0755"
  become: true

- name: Set permissions for i2c devices
  ansible.builtin.copy:
    src: 20-i2c-permissions.rules
    dest: /etc/udev/rules.d/20-i2c-permissions.rules
    group: root
    owner: root
    mode: "0644"
  become: true
