---
- name: Install package lightdm
  pkg_manager:
    name: lightdm, lightdm-gtk-greeter
  become: yes
  become_user: "{{install_user}}"

- name: Create configuration for lightdm
  copy:
    src: lightdm.conf
    dest: /etc/lightdm/lightdm.conf
    mode: 0644
    group: root
    owner: root
  become: yes

- name: Create session wrapper for lightdm
  copy:
    src: lightdm_session.sh
    dest: /etc/lightdm/lightdm_session.sh
    mode: 0755
    group: root
    owner: root
  become: yes

- name: Enable lightdm service
  service:
    name: lightdm.service
    enabled: yes
  become: yes
