---
- name: Install package lightdm
  pkg_manager:
    name: lightdm, lightdm-gtk-greeter
    command: install
  become: true
  become_user: "{{ install_user }}"

- name: Create configuration for lightdm
  ansible.builtin.copy:
    src: lightdm.conf
    dest: /etc/lightdm/lightdm.conf
    group: root
    owner: root
    mode: "0644"
  become: true

- name: Create configuration for lightdm users
  ansible.builtin.copy:
    src: users.conf
    dest: /etc/lightdm/users.conf
    group: root
    owner: root
    mode: "0644"
  become: true

- name: Create session wrapper for lightdm
  ansible.builtin.copy:
    src: lightdm_session.sh
    dest: /etc/lightdm/lightdm_session.sh
    group: root
    owner: root
    mode: "0755"
  become: true

- name: Enable lightdm service
  ansible.builtin.service:
    name: lightdm.service
    enabled: true
  become: true
