---
- name: Install package ssdm
  pkg_manager:
    name: ssdm
    command: install
  become: true
  become_user: "{{ install_user }}"

- name: Create configuration for ssdm
  ansible.builtin.copy:
    src: zz_sddm.conf
    dest: /etc/sddm.conf.d/zz_sddm.conf
    group: root
    owner: root
    mode: "0644"
  become: true

- name: Create session wrapper for ssdm
  ansible.builtin.copy:
    src: sddm_xsession.sh
    dest: /etc/sddm.conf.d/sddm_xsession.sh
    group: root``
    owner: root
    mode: "0755"
  become: true

- name: Enable sddm service
  ansible.builtin.service:
    name: sddm.service
    enabled: true
  become: true
