---
- name: Install package sddm
  pkg_manager:
    name: sddm
    command: install
  become: true
  become_user: "{{ install_user }}"

- name: Create configuration for sddm
  ansible.builtin.copy:
    src: zz_sddm.conf
    dest: /etc/sddm.conf.d/zz_sddm.conf
    group: root
    owner: root
    mode: "0644"
  become: true

- name: Enable sddm service
  ansible.builtin.service:
    name: sddm.service
    enabled: true
  become: true
