---
- name: Install package for xorg
  pkg_manager:
    name: xorg-server, xorg-xinit
  become: yes
  become_user: "{{install_user}}"

- name: Configure keyboard
  copy:
    src: 20-keyboard.conf
    dest: /etc/X11/xorg.conf.d/20-keyboard.conf
    mode: 0755
    group: root
    owner: root
  become: yes

- name: Configure touchpad
  copy:
    src: 20-touchpad.conf
    dest: /etc/X11/xorg.conf.d/20-touchpad.conf
    mode: 0755
    group: root
    owner: root
  become: yes
  when: hostname_id == "xnote" or hostname_id == "worknote"

- name: Configure monitor
  copy:
    src: 90-monitor.conf
    dest: /etc/X11/xorg.conf.d/90-monitor.conf
    mode: 0755
    group: root
    owner: root
  become: yes
  when: hostname_id == "archhost"
