---
- name: Install package for xorg
  pkg_manager:
    name: xorg-server, xorg-xinit
    command: install
  become: true
  become_user: "{{ install_user }}"

- name: Configure keyboard
  ansible.builtin.copy:
    src: 20-keyboard.conf
    dest: /etc/X11/xorg.conf.d/20-keyboard.conf
    group: root
    owner: root
    mode: "0755"
  become: true

- name: Configure touchpad
  ansible.builtin.copy:
    src: 20-touchpad.conf
    dest: /etc/X11/xorg.conf.d/20-touchpad.conf
    group: root
    owner: root
    mode: "0755"
  become: true
  when: hostname_id == "xnote" or hostname_id == "worknote"

- name: Configure monitor
  ansible.builtin.copy:
    src: 90-monitor.conf
    dest: /etc/X11/xorg.conf.d/90-monitor.conf
    group: root
    owner: root
    mode: "0755"
  become: true
  when: hostname_id == "master"
