apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ name }}
  namespace: {{ namespace }}
spec:
  acme:
    email: {{ email_for_letsencrypt }}
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: "{{ name }}-account-key"
    solvers:
    - http01:
        ingress:
          ingressTemplate:
            metadata:
              annotations:
                "traefik.ingress.kubernetes.io/frontend-entry-points": "http"
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ name }}
  namespace: {{ namespace }}
spec:
  secretName: {{ cert_secret }}
  dnsNames:
  - {{ lh_domain }}
  - {{ ci_domain }}
  - {{ iot_domain }}
  - {{ root_domain }}
  - {{ test_domain }}
  - {{ oauth_domain }}
  - {{ pgadmin_domain }}
  - {{ registry_domain }}
  issuerRef:
    name: {{ name }}
    kind: Issuer
