apiVersion: v1
kind: PersistentVolume
metadata:
  name: "{{ volume_name }}"
  namespace: "{{ namespace }}"
spec:
  capacity:
    storage: "{{ volume_size }}"
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: "{{ volume_path }}"
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - server
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "{{ volume_name }}"
  namespace: "{{ namespace }}"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "{{ volume_size }}"
  storageClassName: local-storage
  volumeName: "{{ volume_name }}"
