secret:
  POSTGRESQL_PASSWORD: {{ postgresql_password }}
  POSTGRESQL_ARCHIVE_TIMEOUT: "600"
  WALG_COMPRESSION_METHOD: "brotli"
  WALG_BACKUP_TIME: "0 6 * * *"
  WALG_DELTA_MAX_STEPS: "6"
  WALG_BACKUP_DEL_RETAIN: "4"

persistence:
  psql-data:
    enabled: true
    type: pvc
    existingClaim: psql-data
  psql-backup:
    enabled: true
    type: pvc
    existingClaim: psql-backup
