---
- name: Custom setup
  setup:
    gather_subset:
      - '!all'
      - '!any'

- name: Find distro name
  shell: cat /etc/os-release | grep "^ID=" | cut -d'=' -f2-
  register: reg_distro
  changed_when: false

- name: Set common facts
  set_fact:
    main_user: rean
    install_user: aur_builder
    is_chroot: "{{ is_chroot_param }}"
    root_dir: "{{ inventory_dir }}"
    packages_dir: "{{ inventory_dir }}/common/files"
    x86_64: "{{ ansible_facts['architecture'] == 'x86_64' }}"
    arm: "{{ansible_facts['architecture'] == 'armv7l'}}"
    distro: "{{reg_distro.stdout}}"

- name: Find board uuid for x86_64
  shell: cat /sys/class/dmi/id/product_name
  register: reg_product_name_x86_64
  changed_when: false
  become: yes
  when: x86_64

- name: Find board uuid for armv7l
  shell: grep -Po '^Serial\s*:\s*\K[[:xdigit:]]{16}' /proc/cpuinfo
  register: reg_product_name_armv7l
  changed_when: false
  when: arm

# distro: "arch" or "archarm" or "manjaro"
# boot: "nvram_write_enble"|"nvram_write_disable" and ["crypto_home", "textonly"]
# network_type: ["wired", "wired_old", "wireless"]
# virtualization: "none" or "kvm_qemu" or "kvm_libvirt"
# gui: "none" or ["lightdm", "awesome", "kde"]
# develop: "none" or ["std", "cpp", "python", "go", "rust", "rust3D", "protobuf", "sqlite", "android"]
# monitoring: "none" or ["std", "notebook", "hddtemp", "ups"]
# roles: "none" or ["font", "docker", "automount", "web", "game", "messengers", "audio", "media", "pdf", "office", "file_managers", "torrent", "spell_checkers", "plex", "work", "repository"]

- name: Set archhost facts
  set_fact:
    hostname_id: "archhost"
    boot: "nvram_write_disable"
    add_dop_user: False
    network_type: "wired"
    set_ssh_access_keys: True
    virtualization: "kvm_qemu"
    gui: "lightdm,awesome"
    develop: "std,cpp,python,go,protobuf"
    monitoring: "std,hddtemp"
    roles: "font,docker,automount,web,game,messengers,audio,media,pdf,office,file_managers,torrent,spell_checkers,work,repository"
    swap_size: 35
    swappiness: 10
    packages_file: "{{packages_dir}}/packages.py"
  when: x86_64 and reg_product_name_x86_64.stdout == 'MS-7978'

- name: Set master facts
  set_fact:
    hostname_id: "master"
    boot: "nvram_write_enble"
    add_dop_user: False
    network_type: "wired,wireless"
    set_ssh_access_keys: True
    virtualization: "none"
    gui: "lightdm,awesome,kde"
    develop: "std,cpp,python,go,protobuf"
    monitoring: "std,hddtemp"
    roles: "font,docker,automount,web,game,messengers,audio,media,pdf,office,file_managers,torrent,spell_checkers,work,repository"
    swap_size: 20
    swappiness: 10
    packages_file: "{{packages_dir}}/packages.py"
  when: x86_64 and reg_product_name_x86_64.stdout == 'MS-7C90'

- name: Set xnote facts (xiaomi)
  set_fact:
    hostname_id: "xnote"
    boot: "nvram_write_disable"
    add_dop_user: True
    network_type: "wired,wireless"
    set_ssh_access_keys: True
    virtualization: "none"
    gui: "lightdm,awesome,kde"
    develop: "std,cpp,python,go,protobuf"
    monitoring: "std,notebook,hddtemp"
    roles: "font,docker,automount,web,game,messengers,audio,media,pdf,office,file_managers,spell_checkers,work,repository"
    swap_size: 8
    swappiness: 20
    packages_file: "{{packages_dir}}/packages.py"
  when: x86_64 and reg_product_name_x86_64.stdout == 'TM1613'

- name: Set worknote facts
  set_fact:
    hostname_id: "worknote"
    boot: "nvram_write_disable"
    add_dop_user: False
    network_type: "wired,wireless"
    set_ssh_access_keys: True
    virtualization: "none"
    gui: "lightdm,awesome,kde"
    develop: "std,cpp,python,go,protobuf"
    monitoring: "std,notebook,hddtemp"
    roles: "font,docker,web,messengers,audio,media,pdf,office,file_managers,spell_checkers,work,repository"
    swap_size: 35
    swappiness: 10
    packages_file: "{{packages_dir}}/packages.py"
  when: x86_64 and reg_product_name_x86_64.stdout == 'Latitude 5480'

- name: Set archsrv facts
  set_fact:
    hostname_id: "archsrv"
    boot: "nvram_write_enble"
    add_dop_user: False
    network_type: "wired"
    set_ssh_access_keys: False
    virtualization: "none"
    gui: "none"
    develop: "none"
    monitoring: "std,hddtemp"
    roles: "docker,automount,plex"
    swap_size: 35
    swappiness: 10
    packages_file: "{{packages_dir}}/packages.py"
  when: x86_64 and reg_product_name_x86_64.stdout == 'System Product Name'

- name: Set hass facts
  set_fact:
    hostname_id: "hass"
    boot: "nvram_write_enble"
    add_dop_user: False
    network_type: "wired_old"
    set_ssh_access_keys: False
    virtualization: "none"
    gui: "none"
    develop: "none"
    monitoring: "std,hddtemp"
    roles: "none"
    swap_size: 1
    swappiness: 1
    packages_file: "{{packages_dir}}/packages_hass.py"
  when: arm and reg_product_name_armv7l.stdout == '00000000bed57e85'

- name: Set KVM test facts
  set_fact:
    hostname_id: "kvmtest"
    boot: "nvram_write_disable,crypto_home,textonly"
    add_dop_user: False
    network_type: "wired"
    set_ssh_access_keys: True
    virtualization: "none"
    gui: "lightdm,awesome,kde"
    develop: "std,cpp,python,go,protobuf"
    monitoring: "std,hddtemp"
    roles: "font,docker,web,messengers,audio,media,pdf,office,file_managers,spell_checkers,repository"
    swap_size: 4
    swappiness: 1
    packages_file: "{{packages_dir}}/packages.py"
  when: x86_64 and reg_product_name_x86_64.stdout == 'Standard PC (Q35 + ICH9, 2009)'
