---
- name: Custom setup
  setup:
    gather_subset:
      - '!all'
      - '!any'

- name: Set common facts
  set_fact:
    main_user: rean
    install_user: aur_builder
    is_chroot: "{{ is_chroot_param }}"
    root_dir: "{{ inventory_dir }}"
    packages_dir: "{{ inventory_dir }}/common/files"
    x86_64: "{{ ansible_facts['architecture'] == 'x86_64' }}"
    arm: "{{ansible_facts['architecture'] == 'armv7l'}}"

- name: Find board uuid for x86_64
  shell: cat /sys/class/dmi/id/product_name
  register: reg_product_name_x86_64
  changed_when: false
  become: yes
  when: x86_64

- name: Find board uuid for armv7l
  shell: grep -Po '^Serial\s*:\s*\K[[:xdigit:]]{16}' /proc/cpuinfo
  register: reg_product_name_armv7l
  changed_when: false
  when: arm

# distro: "arch" or "arch_arm" or "manjaro"
# network_type: "lan" or ""lan_old" or "wifi"
# virtualization: "none" or "kvm_qemu" or "kvm_libvirt"
# develop: "none" or ["utils", "cpp", "python", "go", "rust", "rust3D", "protobuf", "sqlite", "android"]
# roles: "none" or ["font", "docker", "automount", "hddtemp", "repository", "dotfiles"]
# gui: "none" or ["lightdm", "awesome", "cinnamon", "notebook"]

- name: Set archhost facts
  set_fact:
    hostname_id: "archhost"
    distro: "arch"
    add_dop_user: False
    network_type: "lan"
    set_ssh_access_keys: True
    virtualization: "kvm_qemu"
    develop: "utils,cpp,python,go,protobuf"
    roles: "font,docker,automount,hddtemp,repository,dotfiles"
    gui: "lightdm,awesome"
    boot_ssd: True
    swap_size: 35
    swappiness: 1
    packages_file: "{{packages_dir}}/packages_desktop.py"
  when: x86_64 and reg_product_name_x86_64.stdout == 'MS-7978'

- name: Set archnote facts (xiaomi)
  set_fact:
    hostname_id: "archnote"
    distro: "arch"
    add_dop_user: True
    network_type: "wifi"
    set_ssh_access_keys: True
    virtualization: "none"
    develop: "utils,cpp,python,go,protobuf"
    roles: "font,docker,automount,hddtemp,repository,dotfiles"
    gui: "lightdm,awesome,cinnamon,notebook"
    boot_ssd: True
    swap_size: 8
    swappiness: 20
    packages_file: "{{packages_dir}}/packages_desktop.py"
  when: x86_64 and reg_product_name_x86_64.stdout == 'TM1613'

- name: Set archsrv facts
  set_fact:
    hostname_id: "archsrv"
    distro: "arch"
    add_dop_user: False
    network_type: "lan"
    set_ssh_access_keys: False
    virtualization: "none"
    develop: "none"
    roles: "docker,automount,hddtemp"
    gui: "none"
    boot_ssd: False
    swap_size: 35
    swappiness: 1
    packages_file: "{{packages_dir}}/packages_archsrv.py"
  when: x86_64 and reg_product_name_x86_64.stdout == 'System Product Name'

- name: Set hass facts
  set_fact:
    hostname_id: "hass"
    distro: "arch_arm"
    add_dop_user: False
    network_type: "lan_old"
    set_ssh_access_keys: False
    virtualization: "none"
    develop: "none"
    roles: "hddtemp"
    gui: "none"
    boot_ssd: False
    swap_size: 1
    swappiness: 1
    packages_file: "{{packages_dir}}/packages_hass.py"
  when: arm and reg_product_name_armv7l.stdout == '00000000bed57e85'
