---
- name: Create dirs for font
  ansible.builtin.file:
    path: /usr/share/fonts/PragmataPro
    state: directory
    group: root
    owner: root
    mode: "0555"
  become: true

# ansible-vault decrypt
# ansible-vault encrypt
- name: Copy fonts
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "/usr/share/fonts/PragmataPro/PragmataPro-{{ item }}"
    group: root
    owner: root
    mode: "0444"
  loop:
    - Bold.otf
    - BoldItalic.otf
    - Italic.otf
    - Regular.otf
  become: true

- name: Copy fonts
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "/usr/share/fonts/OTF/Font Awesome 6 Pro-{{ item }}"
    group: root
    owner: root
    mode: "0444"
  loop:
    - Light-300.otf
    - Regular-400.otf
    - Solid-900.otf
    - Thin-100.otf
  become: true

- name: Install first fonts packages
  pkg_manager:
    name: ttf-ms-fonts,ttf-fixedsys-excelsior-linux,ttf-droid,ttf-dejavu,ttf-ubuntu-font-family,inter-font
    command: install
  become: true
  become_user: "{{ install_user }}"

- name: Install second fonts packages
  pkg_manager:
    name: ttf-font-awesome,noto-fonts-emoji,ttf-material-design-icons-git,ttf-material-symbols-variable-git,adobe-source-code-pro-fonts
    command: install
  become: true
  become_user: "{{ install_user }}"

- name: Update fonts
  ansible.builtin.command: fc-cache -fr
  changed_when: false
