---
- name: Create dirs for font
  ansible.builtin.file:
    path: /usr/share/fonts/PragmataPro
    state: directory
    group: root
    owner: root
    mode: "0555"
  become: true

# ansible-vault decrypt
# ansible-vault encrypt
- name: Copy fonts
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "/usr/share/fonts/PragmataPro/PragmataPro-{{ item }}"
    group: root
    owner: root
    mode: "0444"
  loop:
    - Bold.otf
    - BoldItalic.otf
    - Italic.otf
    - Regular.otf
  become: true

- name: Install fonts packages
  pkg_manager:
    name: ttf-ms-fonts,ttf-tahoma,ttf-fixedsys-excelsior-linux,ttf-droid,ttf-dejavu,ttf-ubuntu-font-family,noto-fonts-emoji,adobe-source-code-pro-fonts
    command: install
  become: true
  become_user: "{{ install_user }}"

- name: Update fonts
  ansible.builtin.command: fc-cache -fr
  changed_when: false
