---
- name: Create dirs for font
  file:
    path: /usr/share/fonts/PragmataPro
    state: directory
    mode: 0555
    group: root
    owner: root
  become: yes

# ansible-vault decrypt 
# ansible-vault encrypt 
- name: Copy fonts
  copy:
    src: "{{item}}"
    dest: /usr/share/fonts/PragmataPro/PragmataPro-{{item}}
    mode: 0444    
    group: root
    owner: root
  loop:
    - Bold.otf
    - BoldItalic.otf
    - Italic.otf
    - Regular.otf
  become: yes

- name: Install fonts packages
  pkg_manager:
    name: ttf-ms-fonts,ttf-tahoma,ttf-fixedsys-excelsior-linux,ttf-droid,ttf-dejavu,ttf-ubuntu-font-family,adobe-source-code-pro-fonts

- name: Update fonts
  shell: fc-cache -fr
  changed_when: false
