---
- name: Copy ssh config for git
  ansible.builtin.copy:
    src: git_config
    dest: "/home/{{ main_user }}/.ssh/config"
    group: "{{ main_user }}"
    owner: "{{ main_user }}"
    mode: "0600"

- name: Install github keys
  ansible.builtin.copy:
    content: "{{ item.key }}"
    dest: "/home/{{ main_user }}/.ssh/{{ item.name }}"
    group: "{{ main_user }}"
    owner: "{{ main_user }}"
    mode: "0600"
  loop:
    - { key: "{{ github_private_key }}", name: "github" }
  loop_control:
    label: "{{ item.name }}"
