---
- name: Copy ssh config
  copy:
    src: config
    dest: "/home/{{ main_user }}/.ssh/config"
    mode: 0400
    group: users
    owner: "{{ main_user }}"

- name: Copy ansible ssh config
  copy:
    src: ansible_config
    dest: "/home/{{ main_user }}/.ssh/ansible_config"
    mode: 0400
    group: users
    owner: "{{ main_user }}"

- name: Install ssh keys
  copy:
    content: "{{ item.key }}"
    dest: "/home/{{ main_user }}/.ssh/{{ item.name }}"
    mode: 0400
    group: users
    owner: "{{ main_user }}"
  loop:
    - { key: "{{ aur_private_key }}", name: "aur" }
    - { key: "{{ aur_public_key }}", name: "aur.pub" }
    - { key: "{{ hass_private_key }}", name: "hass" }
    - { key: "{{ master_private_key }}", name: "master" }
    - { key: "{{ myoffice_private_key }}", name: "myoffice" }
    - { key: "{{ respeaker_private_key }}", name: "respeaker" }
    - { key: "{{ vdsina_private_key }}", name: "vdsina" }
    - { key: "{{ vdsina_public_key }}", name: "vdsina.pub" }
    - { key: "{{ server_private_key }}", name: "server" }
    - { key: "{{ vscale_private_key }}", name: "vscale" }
    - { key: "{{ worknote_private_key }}", name: "worknote" }
    - { key: "{{ xnote_private_key }}", name: "xnote" }
  loop_control:
    label: "{{ item.name }}"
