---
- name: Copy ssh config
  copy:
    src: config
    dest: "/home/{{main_user}}/.ssh/config"
    mode: 0400
    group: users
    owner: "{{main_user}}"

- name: Copy ansible ssh config
  copy:
    src: ansible_config
    dest: "/home/{{main_user}}/.ssh/ansible_config"
    mode: 0400
    group: users
    owner: "{{main_user}}"

- name: Install ssh keys
  copy:
    content: "{{item.key}}"
    dest: "/home/{{main_user}}/.ssh/{{item.name}}"
    mode: 0400
    group: users
    owner: "{{main_user}}"
  loop:
    - { key: "{{ aur_private_key }}", name: "aur" }
    - { key: "{{ aur_public_key }}", name: "aur.pub" }
    - { key: "{{ work_private_key }}", name: "id_rsa" }
    - { key: "{{ work_public_key }}", name: "id_rsa.pub" }
    - { key: "{{ vscale_private_key }}", name: "vscale" }
    - { key: "{{ hass_private_key }}", name: "hass" }
    - { key: "{{ respeaker_private_key }}", name: "respeaker" }
    - { key: "{{ archhost_private_key }}", name: "archhost" }
    - { key: "{{ master_private_key }}", name: "master" }
    - { key: "{{ xnote_private_key }}", name: "xnote" }
    - { key: "{{ worknote_private_key }}", name: "worknote" }
    - { key: "{{ archsrv_private_key }}", name: "archsrv" }
  loop_control:
    label: "{{ item.name }}"
