---
- name: Create ssh directory
  file:
    path: "/home/{{main_user}}/.ssh"
    state: directory
    mode: 0700
    group: users
    owner: "{{main_user}}"

# ansible-vault decrypt secrets.yml
# ansible-vault encrypt secrets.yml
- name: Include vars with keys
  include_vars:
    file: secrets.yml

- include: keys.yml
  when: set_ssh_access_keys == True

- include: sshd.yml
- include: known_hosts.yml