---
# ansible-vault decrypt secrets.yml
# ansible-vault encrypt secrets.yml
- name: Include vars with keys
  include_vars:
    file: secrets.yml

- name: Create ssh directory
  ansible.builtin.file:
    path: "/home/{{ main_user }}/.ssh"
    state: directory
    group: "{{ main_user }}"
    owner: "{{ main_user }}"
    mode: "0700"

- import_tasks: pub_keys.yml

- import_tasks: private_all_keys.yml
  when: ssh_access == "all"

- import_tasks: private_work_keys.yml
  when: ssh_access == "work"

- import_tasks: private_github_keys.yml
  when: ssh_access == "github"

- import_tasks: sshd.yml

- import_tasks: known_hosts.yml
  when: ssh_access == "all" or ssh_access == "github"
