---
- name: Copy ssh config
  ansible.builtin.template:
    src: config
    dest: "/home/{{ main_user }}/.ssh/config"
    group: "{{ main_user }}"
    owner: "{{ main_user }}"
    mode: "0600"
  become: true

- name: Copy ansible ssh config
  ansible.builtin.template:
    src: ansible_config
    dest: "/home/{{ main_user }}/.ssh/ansible_config"
    group: "{{ main_user }}"
    owner: "{{ main_user }}"
    mode: "0600"

- name: Add private keys
  ansible.builtin.copy:
    content: "{{ item.key }}"
    dest: "/home/{{ main_user }}/.ssh/{{ item.name }}"
    group: "{{ main_user }}"
    owner: "{{ main_user }}"
    mode: "0600"
  loop:
    - { key: "{{ aur_private_key }}", name: "aur" }
    - { key: "{{ github_private_key }}", name: "github" }
    - { key: "{{ hass_private_key }}", name: "hass" }
    - { key: "{{ master_private_key }}", name: "master" }
    - { key: "{{ myoffice_private_key }}", name: "myoffice" }
    - { key: "{{ respeaker_private_key }}", name: "respeaker" }
    - { key: "{{ server_private_key }}", name: "server" }
    - { key: "{{ vdsina_private_key }}", name: "vdsina" }
    - { key: "{{ vscale_private_key }}", name: "vscale" }
    - { key: "{{ weaselproxy_private_key }}", name: "weaselproxy" }
    - { key: "{{ worknote_private_key }}", name: "worknote" }
    - { key: "{{ xnote_private_key }}", name: "xnote" }
  loop_control:
    label: "{{ item.name }}"
