---
- name: Add public key for hass
  ansible.builtin.copy:
    content: "{{ hass_public_key }}"
    dest: "/home/{{ main_user }}/.ssh/authorized_keys"
    group: "{{ main_user }}"
    owner: "{{ main_user }}"
    mode: "0644"
  when: hostname_id == "hass"

- name: Add public key for server
  ansible.builtin.copy:
    content: "{{ server_public_key }}"
    dest: "/home/{{ main_user }}/.ssh/authorized_keys"
    group: "{{ main_user }}"
    owner: "{{ main_user }}"
    mode: "0644"
  when: hostname_id == "server"

- name: Add public key for master
  ansible.builtin.copy:
    content: "{{ master_public_key }}"
    dest: "/home/{{ main_user }}/.ssh/authorized_keys"
    group: "{{ main_user }}"
    owner: "{{ main_user }}"
    mode: "0644"
  when: hostname_id == "master"

- name: Add public key for xnote
  ansible.builtin.copy:
    content: "{{ xnote_public_key }}"
    dest: "/home/{{ main_user }}/.ssh/authorized_keys"
    group: "{{ main_user }}"
    owner: "{{ main_user }}"
    mode: "0644"
  when: hostname_id == "xnote"

- name: Add public key for worknote
  ansible.builtin.copy:
    content: "{{ worknote_public_key }}"
    dest: "/home/{{ main_user }}/.ssh/authorized_keys"
    group: "{{ main_user }}"
    owner: "{{ main_user }}"
    mode: "0644"
  when: hostname_id == "worknote"

- name: Add public key for weaselproxy
  ansible.builtin.copy:
    content: "{{ weaselproxy_public_key }}"
    dest: "/home/{{ main_user }}/.ssh/authorized_keys"
    group: "{{ main_user }}"
    owner: "{{ main_user }}"
    mode: "0644"
  when: hostname_id == "weaselproxy"

- name: Add public key for pqhost
  ansible.builtin.copy:
    content: "{{ pqhost_public_key }}"
    dest: "/home/{{ main_user }}/.ssh/authorized_keys"
    group: "{{ main_user }}"
    owner: "{{ main_user }}"
    mode: "0644"
  when: hostname_id == "pqhost"

- name: Add public keys
  ansible.builtin.copy:
    content: "{{ item.key }}"
    dest: "/home/{{ main_user }}/.ssh/{{ item.name }}.pub"
    group: "{{ main_user }}"
    owner: "{{ main_user }}"
    mode: "0600"
  loop:
    - { key: "{{ pqhost_public_key }}", name: "pqhost" }
    - { key: "{{ weaselproxy_public_key }}", name: "weaselproxy" }
  loop_control:
    label: "{{ item.name }}"
  when: ssh_access == "all"
