---
- name: Add public key for hass
  ansible.builtin.copy:
    content: "{{ hass_public_key }}"
    dest: "/home/{{ main_user }}/.ssh/authorized_keys"
    mode: "0644"
    owner: "{{ main_user }}"
    group: "{{ main_user }}"
  when: hostname_id == "hass"

- name: Add public key for server
  ansible.builtin.copy:
    content: "{{ server_public_key }}"
    dest: "/home/{{ main_user }}/.ssh/authorized_keys"
    mode: "0644"
    owner: "{{ main_user }}"
    group: "{{ main_user }}"
  when: hostname_id == "server"

- name: Add public key for master
  ansible.builtin.copy:
    content: "{{ master_public_key }}"
    dest: "/home/{{ main_user }}/.ssh/authorized_keys"
    mode: "0644"
    owner: "{{ main_user }}"
    group: "{{ main_user }}"
  when: hostname_id == "master"

- name: Add public key for xnote
  ansible.builtin.copy:
    content: "{{ xnote_public_key }}"
    dest: "/home/{{ main_user }}/.ssh/authorized_keys"
    mode: "0644"
    owner: "{{ main_user }}"
    group: "{{ main_user }}"
  when: hostname_id == "xnote"

- name: Add public key for worknote
  ansible.builtin.copy:
    content: "{{ worknote_public_key }}"
    dest: "/home/{{ main_user }}/.ssh/authorized_keys"
    mode: "0644"
    owner: "{{ main_user }}"
    group: "{{ main_user }}"
  when: hostname_id == "worknote"

- name: Add public key for vdsina
  ansible.builtin.copy:
    content: "{{ vdsina_public_key }}"
    dest: "/home/{{ main_user }}/.ssh/authorized_keys"
    mode: "0644"
    owner: "{{ main_user }}"
    group: "{{ main_user }}"
  when: hostname_id == "vdsina"
