---
- name: Add public key for hass
  copy:
    content: "{{ hass_public_key }}"
    dest: "/home/{{ main_user }}/.ssh/authorized_keys"
    mode: 0400
    group: users
    owner: "{{ main_user }}"
  when: hostname_id == "hass"

- name: Add public key for server
  copy:
    content: "{{ server_public_key }}"
    dest: "/home/{{ main_user }}/.ssh/authorized_keys"
    mode: 0400
    group: users
    owner: "{{ main_user }}"
  when: hostname_id == "server"

- name: Add public key for master
  copy:
    content: "{{ master_public_key }}"
    dest: "/home/{{ main_user }}/.ssh/authorized_keys"
    mode: 0400
    group: users
    owner: "{{ main_user }}"
  when: hostname_id == "master"

- name: Add public key for xnote
  copy:
    content: "{{ xnote_public_key }}"
    dest: "/home/{{ main_user }}/.ssh/authorized_keys"
    mode: 0400
    group: users
    owner: "{{ main_user }}"
  when: hostname_id == "xnote"

- name: Add public key for worknote
  copy:
    content: "{{ worknote_public_key }}"
    dest: "/home/{{ main_user }}/.ssh/authorized_keys"
    mode: 0400
    group: users
    owner: "{{ main_user }}"
  when: hostname_id == "worknote"

- name: Install package for ssh server
  pkg_manager:
    name: openssh
  become: yes
  become_user: "{{ install_user }}"

- name: Copy sshd config
  copy:
    src: sshd_config
    dest: "/etc/ssh/sshd_config"
    mode: 0644
    group: root
    owner: root
  become: yes

- name: Enable service sshd
  service:
    name: sshd.service
    enabled: yes
  become: yes
