---
- name: Install arch package for ssh server
  pkg_manager:
    name: openssh
  when: distro == "arch" or distro == "archarm"
  become: true
  become_user: "{{ install_user }}"

- name: Copy sshd config
  copy:
    src: sshd_config
    dest: "/etc/ssh/sshd_config"
    mode: 0644
    group: root
    owner: root
  become: true

- name: Enable service sshd
  service:
    name: sshd.service
    enabled: true
  become: true
