---
- name: Add public key for archhost
  copy:
    content: "{{archhost_public_key}}"
    dest: "/home/{{main_user}}/.ssh/authorized_keys"
    mode: 0400
    group: users
    owner: "{{main_user}}"
  when: hostname_id == "archhost"

- name: Add public key for archnote
  copy:
    content: "{{archnote_public_key}}"
    dest: "/home/{{main_user}}/.ssh/authorized_keys"
    mode: 0400
    group: users
    owner: "{{main_user}}"
  when: hostname_id == "archnote"

- name: Add public key for archsrv
  copy:
    content: "{{archsrv_public_key}}"
    dest: "/home/{{main_user}}/.ssh/authorized_keys"
    mode: 0400
    group: users
    owner: "{{main_user}}"
  when: hostname_id == "archsrv"

- name: Copy sshd config
  copy:
    src: sshd_config
    dest: "/etc/ssh/sshd_config"
    mode: 0644
    group: root
    owner: root
  become: yes
  when: set_ssh_access_keys == True

- name: Install package for ssh server
  pacman:
    name: openssh
    state: present
  become: yes

- name: Enable service sshd for chroot
  service:
    name: sshd.service
    enabled: yes
  become: yes
  when: is_chroot == True

- name: Enable and start service sshd
  service:
    name: sshd.service
    enabled: yes
    state: started
  become: yes
  when: is_chroot == False
