---
- name: Install arch package for ssh server
  pkg_manager:
    name: openssh
    command: install
  become: true
  become_user: "{{ install_user }}"
  when: os_family == "arch"

- name: Install debian package for ssh server
  ansible.builtin.apt:
    name: openssh-server
    state: present
  become: true
  when: os_family == "debian"

- name: Copy sshd config
  ansible.builtin.template:
    src: sshd_config
    dest: "/etc/ssh/sshd_config"
    owner: root
    group: root
    mode: "0644"
  become: true

- name: Enable service sshd
  ansible.builtin.service:
    name: sshd.service
    enabled: true
  become: true
