---
- name: Add public key for archhost
  copy:
    content: "{{archhost_public_key}}"
    dest: "/home/{{main_user}}/.ssh/authorized_keys"
    mode: 0400
    group: users
    owner: "{{main_user}}"
  when: hostname_id == "archhost"

- name: Add public key for xnote
  copy:
    content: "{{xnote_public_key}}"
    dest: "/home/{{main_user}}/.ssh/authorized_keys"
    mode: 0400
    group: users
    owner: "{{main_user}}"
  when: hostname_id == "xnote"

- name: Add public key for worknote
  copy:
    content: "{{worknote_public_key}}"
    dest: "/home/{{main_user}}/.ssh/authorized_keys"
    mode: 0400
    group: users
    owner: "{{main_user}}"
  when: hostname_id == "worknote"

- name: Add public key for archsrv
  copy:
    content: "{{archsrv_public_key}}"
    dest: "/home/{{main_user}}/.ssh/authorized_keys"
    mode: 0400
    group: users
    owner: "{{main_user}}"
  when: hostname_id == "archsrv"

- name: Add public key for hass
  copy:
    content: "{{hass_public_key}}"
    dest: "/home/{{main_user}}/.ssh/authorized_keys"
    mode: 0400
    group: users
    owner: "{{main_user}}"
  when: hostname_id == "hass"

- name: Install package for ssh server
  pkg_manager:
    name: openssh
  become: yes
  become_user: "{{install_user}}"

- name: Copy sshd config
  copy:
    src: sshd_config
    dest: "/etc/ssh/sshd_config"
    mode: 0644
    group: root
    owner: root
  become: yes

- name: Enable service sshd for chroot
  service:
    name: sshd.service
    enabled: yes
  become: yes
  when: is_chroot == True

- name: Enable and start service sshd
  service:
    name: sshd.service
    enabled: yes
    state: started
  become: yes
  when: is_chroot == False
