---
- name: Install packages for hddtemp
  pkg_manager:
    name: hddtemp, smartmontools
  become: true
  become_user: "{{ install_user }}"

- name: Create hddtemp service directory
  file:
    path: /etc/systemd/system/hddtemp.service.d
    state: directory
    mode: '0755'
    group: root
    owner: root
  become: true

- name: Remove old hddtemp settings file
  file:
    path: /tmp/customexec.conf
    state: absent
  become: true
  changed_when: false

- name: Create hddtemp settings file
  script: generate.sh > /tmp/customexec.conf
  become: true
  changed_when: false

- name: Install hddtemp settings file
  copy:
    src: /tmp/customexec.conf
    dest: /etc/systemd/system/hddtemp.service.d/customexec.conf
    mode: 0644
    group: root
    owner: root
    remote_src: yes
  become: true
  register: reg_settings

- name: Remove new hddtemp settings file
  file:
    path: /tmp/customexec.conf
    state: absent
  become: true
  changed_when: false

- name: Enable and start hddtemp service
  service:
    name: hddtemp.service
    enabled: yes
    state: started
  become: true

- name: Restart hddtemp service if config changed
  service:
    name: hddtemp.service
    enabled: yes
    state: restarted
  when: reg_settings.changed
  become: true
