---
- name: Install package apcupsd
  pkg_manager:
    name: apcupsd
  become: yes
  become_user: "{{install_user}}"

- name: Configure apcupsd
  copy:
    src: apcupsd.conf
    dest: /etc/apcupsd/apcupsd.conf
    mode: 0644
    group: root
    owner: root
  become: yes

- name: Enable and start apcupsd service
  service:
    name: apcupsd.service
    enabled: yes
    state: started
  become: yes
