---
- name: Install package apcupsd
  pkg_manager:
    name: apcupsd
    command: install
  become: true
  become_user: "{{ install_user }}"

- name: Configure apcupsd
  ansible.builtin.copy:
    src: apcupsd.conf
    dest: /etc/apcupsd/apcupsd.conf
    group: root
    owner: root
    mode: "0644"
  become: true

- name: Enable and start apcupsd service
  ansible.builtin.service:
    name: apcupsd.service
    enabled: true
  become: true
