---
- name: Install package apcupsd
  pkg_manager:
    name: apcupsd
  become: true
  become_user: "{{ install_user }}"

- name: Configure apcupsd
  copy:
    src: apcupsd.conf
    dest: /etc/apcupsd/apcupsd.conf
    mode: 0644
    group: root
    owner: root
  become: true

- name: Enable and start apcupsd service
  service:
    name: apcupsd.service
    enabled: yes
  become: true
