---
- name: Install package go
  pkg_manager:
    name: go

- name: Install go utils without sudo
  command: go get -u {{item}}
  environment:
    GOPATH: /home/{{main_user}}/.local/share/go
  loop:
    - 'github.com/nsf/gocode'
    - 'github.com/rogpeppe/godef'
    - 'github.com/jstemmer/gotags'
    - 'github.com/kisielk/errcheck'
    - 'golang.org/x/tools/cmd/guru'
    - 'github.com/golang/lint/golint'
    - 'golang.org/x/tools/cmd/gorename'
    - 'golang.org/x/tools/cmd/goimports'  

- name: Install go utils with sudo
  command: go get -u {{item}}
  become: yes
  environment:
    GOPATH: /home/{{main_user}}/.local/share/go
  loop:
    - 'golang.org/x/tools/cmd/godoc'
