---
- name: Copy systemd-networkd configuration for new interface
  copy:
    src: wired.network
    dest: /etc/systemd/network/wired.network
    owner: root
    group: root
    mode: 0644
  become: yes
  when: network_type == "lan"

- name: Copy systemd-networkd configuration for old interface
  copy:
    src: eth0.network
    dest: /etc/systemd/network/eth0.network
    owner: root
    group: root
    mode: 0644
  become: yes
  when: network_type == "lan_old"

- name: Create symbolic links for /etc/resolv.conf
  file:
    src: /run/systemd/resolve/resolv.conf
    dest: /etc/resolv.conf
    state: link
    force: yes
  become: yes
  when: is_chroot == False

- name: Enable service systemd-networkd for chroot
  service:
    name: systemd-networkd.service
    enabled: yes
  become: yes
  when: is_chroot == True

- name: Enable and start service systemd-networkd
  service:
    name: systemd-networkd.service
    enabled: yes
    state: started
  become: yes
  when: is_chroot == False

- name: Enable service systemd-resolved for chroot
  service:
    name: systemd-resolved.service
    enabled: yes
  become: yes
  when: is_chroot == True

- name: Enable and start service systemd-resolved
  service:
    name: systemd-resolved.service
    enabled: yes
    state: started
  become: yes
  when: is_chroot == False
