---
- name: Set hostname
  hostname: name={{hostname_id}}
  become: yes
  when: is_chroot == False

- include: lan.yml
  when: install_lan == True

- include: wifi.yml
  when: install_wifi == True and is_chroot == False
