---
- name: Set hostname
  hostname:
    name: "{{hostname_id}}"
  become: yes
  when: is_chroot == False

- include: wireless.yml
  when: '"wireless" in roles.split(",")'

- include: wired.yml

- include: systemd_network.yml
