---
- name: Set hostname
  hostname:
    name: "{{hostname_id}}"
  become: yes
  when: is_chroot == False

- include: lan.yml
  when: network_type == "lan" or network_type == "lan_old"

- include: wifi.yml
  when: network_type == "wifi" and is_chroot == False
