---
- import_tasks: resolv.yml

- import_tasks: systemd_network.yml
  when: "'smd_wired' in network_type.split(',') or 'smd_wireless' in network_type.split(',')"

- import_tasks: network_manager.yml
  when: "'nm_wired' in network_type.split(',') or 'nm_wireless' in network_type.split(',')"
