---
- name: Set hostname
  hostname: name={{hostname_id}}
  when: is_chroot == False
  become: yes

- name: Copy systemd-networkd configuration
  copy:
    src: wired.network
    dest: /etc/systemd/network/wired.network
    owner: root
    group: root
    mode: 0644
  when: install_lan == True and is_chroot == False
  become: yes

- name: Create symbolic links for /etc/resolv.conf
  file:
    src: /run/systemd/resolve/resolv.conf
    dest: /etc/resolv.conf
    state: link
    force: yes
  when: install_lan == True and is_chroot == False
  become: yes

- name: Enable and start service systemd-networkd
  service:
    name: systemd-networkd.service
    enabled: yes
    state: started
  when: install_lan == True and is_chroot == False
  become: yes

- name: Enable and start service systemd-resolved
  service:
    name: systemd-resolved.service
    enabled: yes
    state: started
  when: install_lan == True and is_chroot == False
  become: yes

# ansible-vault decrypt secrets.yml
# ansible-vault encrypt secrets.yml
- name: Include vars for wifi configuration
  include_vars:
    file: secrets.yml
  when: install_wifi == True and is_chroot == False

- name: Copy netctl configuration
  template:
    src: "{{item}}"
    dest: /etc/netctl/{{item}}
    owner: root
    group: root
    mode: 0600
  when: install_wifi == True and is_chroot == False
  become: yes  
  with_items:
    - wlp2s0-Arch5
    - wlp2s0-Arch2

- name: Check that wlp2s0-Arch5 service exists
  stat:
    path: "/etc/systemd/system/multi-user.target.wants/netctl@wlp2s0\\x2dArch5.service"
    get_checksum: no
    get_mime: no
  register: reg_wifi5_service_installed
  when: install_wifi == True and is_chroot == False
  become: yes

- name: Enable wlp2s0-Arch5
  command: netctl enable wlp2s0-Arch5
  when: install_wifi == True and is_chroot == False and reg_wifi5_service_installed.stat.exists == False
  become: yes

- name: Start wlp2s0-Arch5
  command: netctl start wlp2s0-Arch5
  when: install_wifi == True and is_chroot == False and reg_wifi5_service_installed.stat.exists == False
  become: yes
