---
- name: Install networkmanager package
  pkg_manager:
    name: networkmanager
  become: yes
  become_user: "{{install_user}}"

- name: Start and enable service NetworkManager
  service:
    name: NetworkManager.service
    enabled: yes
    state: started
  become: yes
