---
- name: Create symbolic links for /etc/resolv.conf
  file:
    src: /run/systemd/resolve/resolv.conf
    dest: /etc/resolv.conf
    state: link
    force: yes
  become: yes
  when: is_chroot == False

- name: Enable service systemd-networkd for chroot
  service:
    name: systemd-networkd.service
    enabled: yes
  become: yes
  when: is_chroot == True

- name: Start and enable service systemd-networkd for not chroot
  service:
    name: systemd-networkd.service
    enabled: yes
    state: started
  become: yes
  when: is_chroot == False

- name: Enable service systemd-resolved for chroot
  service:
    name: systemd-resolved.service
    enabled: yes
  become: yes
  when: is_chroot == True

- name: Start and enable service systemd-resolved for not chroot
  service:
    name: systemd-resolved.service
    enabled: yes
    state: started
  become: yes
  when: is_chroot == False
