---
# ansible-vault decrypt secrets.yml
# ansible-vault encrypt secrets.yml
- name: Include vars for wifi configuration
  include_vars:
    file: secrets.yml

- name: Copy netctl configuration
  template:
    src: "{{item}}"
    dest: /etc/netctl/{{item}}
    owner: root
    group: root
    mode: 0600
  become: yes
  loop:
    - wlp2s0-Arch5
    - wlp2s0-Arch2

- name: Check that wlp2s0-Arch5 service exists
  stat:
    path: "/etc/systemd/system/multi-user.target.wants/netctl@wlp2s0\\x2dArch5.service"
    get_checksum: no
    get_mime: no
  register: reg_wifi5_service_installed
  become: yes

- name: Enable wlp2s0-Arch5
  command: netctl enable wlp2s0-Arch5
  when: reg_wifi5_service_installed.stat.exists == False
  become: yes

- name: Start wlp2s0-Arch5
  command: netctl start wlp2s0-Arch5
  when: reg_wifi5_service_installed.stat.exists == False
  become: yes
