---
- name: Copy systemd-networkd configuration for modern interface
  copy:
    src: wired.network
    dest: /etc/systemd/network/wired.network
    owner: root
    group: root
    mode: 0644
  become: yes
  when: '"wired" in roles.split(",")'

- name: Copy systemd-networkd configuration for old interface
  copy:
    src: eth0.network
    dest: /etc/systemd/network/eth0.network
    owner: root
    group: root
    mode: 0644
  become: yes
  when: '"wired_old" in roles.split(",")'
