---
- name: Install packages for wireless
  pkg_manager:
    name: iwd
  become: yes
  become_user: "{{install_user}}"

- name: Copy systemd-networkd configuration for wireless interface
  copy:
    src: wireless.network
    dest: /etc/systemd/network/wireless.network
    owner: root
    group: root
    mode: 0644
  become: yes
