---

- name: Create config dir for pulse
  ansible.builtin.file:
    path: "/home/{{ main_user }}/.config/pipewire/pipewire-pulse.conf.d/"
    state: directory
    group: "{{ main_user }}"
    owner: "{{ main_user }}"
    mode: "0755"
    recurse: true

- name: Disable mic autogain for pulse
  ansible.builtin.copy:
    src: 20-pulse-disable-mic-autogain.conf
    dest: "/home/{{ main_user }}/.config/pipewire/pipewire-pulse.conf.d/20-pulse-disable-mic-autogain.conf"
    group: "{{ main_user }}"
    owner: "{{ main_user }}"
    mode: "0644"

- name: Create config dir for pipewire
  ansible.builtin.file:
    path: "/home/{{ main_user }}/.config/pipewire/pipewire.conf.d/"
    state: directory
    group: "{{ main_user }}"
    owner: "{{ main_user }}"
    mode: "0755"
    recurse: true

- name: Disable mic autogain for pipewire
  ansible.builtin.copy:
    src: 20-pipewire-disable-mic-autogain.conf
    dest: "/home/{{ main_user }}/.config/pipewire/pipewire.conf.d/20-pipewire-disable-mic-autogain.conf"
    group: "{{ main_user }}"
    owner: "{{ main_user }}"
    mode: "0644"

- name: Create virtual mics
  ansible.builtin.copy:
    src: 10-vmics.conf
    dest: "/home/{{ main_user }}/.config/pipewire/pipewire.conf.d/10-vmics.conf"
    group: "{{ main_user }}"
    owner: "{{ main_user }}"
    mode: "0644"

- name: Create config dir for wireplumber
  ansible.builtin.file:
    path: "/home/{{ main_user }}/.config/wireplumber/wireplumber.conf.d/"
    state: directory
    group: "{{ main_user }}"
    owner: "{{ main_user }}"
    mode: "0755"
    recurse: true

- name: Disable suspend
  ansible.builtin.copy:
    src: 60-disable-suspend.conf
    dest: "/home/{{ main_user }}/.config/wireplumber/wireplumber.conf.d/60-disable-suspend.conf"
    group: "{{ main_user }}"
    owner: "{{ main_user }}"
    mode: "0644"
  when: hostname_id == "master"
