---
- name: Install pulseaudio
  pkg_manager:
    name: pulseaudio
  become: yes
  become_user: "{{install_user}}"

- name: Add "Jack Headphone Mic" and "Jack Headset Mic"
  copy:
    src: analog-input-internal-mic.conf
    dest: /usr/share/pulseaudio/alsa-mixer/paths/analog-input-internal-mic.conf
    mode: 0644
    group: root
    owner: root
  become: yes
