---
- name: Install pipewire
  pkg_manager:
    name: pipewire, lib32-pipewire, pipewire-audio, pipewire-alsa, pipewire-pulse, pipewire-jack, wireplumber
    command: install
  become: true
  become_user: "{{ install_user }}"

- name: Enable wireplumber systemd user service
  ansible.builtin.systemd_service:
    name: wireplumber
    scope: user
    enabled: true
  when: not is_chroot

- import_tasks: config.yml
