---
- name: Install package nfs-utils
  pkg_manager:
    name: nfs-utils
    command: install
  become: true
  become_user: "{{ install_user }}"

- name: Install servicies for nfs mount
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "/etc/systemd/system/{{ item }}"
    group: root
    owner: root
    mode: "0644"
  become: true
  loop:
    - mnt-nas-backup.mount
    - mnt-nas-backup.automount
    - mnt-nas-downloads.mount
    - mnt-nas-downloads.automount

- name: Enable servicies for nfs mount
  ansible.builtin.service:
    name: "{{ item }}"
    enabled: true
  become: true
  loop:
    - mnt-nas-backup.automount
    - mnt-nas-downloads.automount
