---
- name: Install package nfs-utils
  pkg_manager:
    name: nfs-utils
  become: true
  become_user: "{{ install_user }}"

- name: Install servicies for nfs mount
  copy:
    src: "{{ item }}"
    dest: /etc/systemd/system/{{ item }}
    mode: '0644'
    group: root
    owner: root
  become: true
  loop:
    - mnt-nas-backup.mount
    - mnt-nas-backup.automount
    - mnt-nas-downloads.mount
    - mnt-nas-downloads.automount

- name: Enable servicies for nfs mount
  service:
    name: "{{ item }}"
    enabled: yes
  become: true
  loop:
    - mnt-nas-backup.automount
    - mnt-nas-downloads.automount
