---
# ansible-vault decrypt secrets.yml
# ansible-vault encrypt secrets.yml
- name: Include vars passwords
  include_vars:
    file: secrets.yml

- name: Create group for main user
  ansible.builtin.group:
    name: "{{ main_user }}"
    gid: 1000
    state: present
  when: hostname_id != "weaselproxy"
  become: true

- name: Create main user for home
  ansible.builtin.user:
    name: "{{ main_user }}"
    uid: 1000
    append: true
    create_home: true
    group: rean
    groups: video,audio,storage,power,uucp
    password: "{{ main_user_password }}"
  when: hostname_id == "hass" or
        hostname_id == "server" or
        hostname_id == "master" or
        hostname_id == "xnote" or
        hostname_id == "kvmtest"
  become: true

- name: Create main user for work
  ansible.builtin.user:
    name: "{{ main_user }}"
    uid: 1000
    append: true
    create_home: true
    group: rean
    groups: video,audio,storage,power,uucp
    password: "{{ work_user_password }}"
  when: hostname_id == "worknote"
  become: true

- name: Create main user for pqhost
  ansible.builtin.user:
    name: "{{ main_user }}"
    uid: 1000
    # append: true
    # groups is not set
    create_home: true
    group: rean
    password: "{{ pqhost_user_password }}"
  when: hostname_id == "pqhost"
  become: true

- import_tasks: weaselproxy.yml
  when: hostname_id == "weaselproxy"
