---
- name: Base install respeaker

  hosts: respeaker

  environment:
    PATH: "/pyenv/bin:/pyenv/shims:{{ ansible_env.PATH }}"
    PYENV_ROOT: /pyenv

  vars_files:
    - ../../vars/path.yml

  tasks:
    - include: "{{tasks_dir}}/common/locale.yml"
    - include: "{{tasks_dir}}/common/time.yml"
    - include: "{{tasks_dir}}/common/systemd_cfg.yml"
    - include: "{{tasks_dir}}/respeaker/user.yml"
    - include: "{{tasks_dir}}/respeaker/logger.yml"
    - include: "{{tasks_dir}}/respeaker/remove_unused.yml"
    - include: "{{tasks_dir}}/respeaker/rsync.yml"
    - include: "{{tasks_dir}}/respeaker/pyenv.yml"
