---
- name: Base install respeaker

  hosts: respeaker

  vars_files:
    - ../../vars/path.yml

  tasks:
    - include: "{{tasks_dir}}/common/locale.yml"
    - include: "{{tasks_dir}}/common/time.yml"
    - include: "{{tasks_dir}}/common/systemd_cfg.yml"
    - include: "{{tasks_dir}}/respeaker/user.yml"
