--- # abs_path, without dependencies

- name: Install packages for pyenv
  ansible.builtin.apt:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - libssl-dev
      - zlib1g-dev
      - libbz2-dev
      - libreadline-dev
      - libsqlite3-dev
      - llvm
      - tk-dev
      - libxml2-dev
      - libxmlsec1-dev
      - libffi-dev
  become: true

- name: Create dir for pyenv
  ansible.builtin.file:
    path: /pyenv
    state: directory
    recurse: true
    group: users
    owner: rean
    mode: "0755"
  become: true

- name: Clone pyenv
  ansible.builtin.git:
    repo: https://github.com/pyenv/pyenv.git
    dest: /pyenv
    depth: 1
    update: false
    version: v1.2.7

- name: Check that python 3.7.0 is not installed
  ansible.builtin.stat:
    path: /pyenv/versions/3.7.0
    get_checksum: false
    get_mime: false
  register: python_installed

- name: Install python 3.6.6
  ansible.builtin.command: pyenv install 3.6.6
  when: python_installed.stat.exists == False

- name: add pyenv to bash_profile
  ansible.builtin.template:
    src: "{{files_dir}}/respeaker/home/.bash_profile"
    dest: /home/rean/.bash_profile
    group: users
    owner: rean
    mode: "0644"
