--- # abs_path, without dependencies

- name: Install packages for pyenv
  apt:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - libssl-dev
      - zlib1g-dev
      - libbz2-dev
      - libreadline-dev
      - libsqlite3-dev
      - llvm
      - tk-dev
      - libxml2-dev
      - libxmlsec1-dev
      - libffi-dev
  become: yes

- name: Create dir for pyenv
  file: path=/pyenv state=directory mode=0755 group=users owner=rean recurse=yes
  become: yes

- name: Clone pyenv
  git:
    repo: https://github.com/pyenv/pyenv.git
    dest: /pyenv
    depth: 1
    update: no
    version: v1.2.7

- name: Check that python 3.7.0 is not installed
  stat: path="/pyenv/versions/3.7.0" get_checksum=no get_mime=no
  register: python_installed

- name: Install python 3.7.0
  command: pyenv install 3.7.0
  when: python_installed.stat.exists == False

- name: add pyenv to bash_profile
  template: src="{{files_dir}}/respeaker/home/.bash_profile" dest=/home/rean/.bash_profile mode=0644 group=users owner=rean
