--- # abs_path, without dependencies
- name: Remove unused packages
  ansible.builtin.apt:
    name: "{{ packages }}"
    state: absent
    purge: true
  vars:
    packages:
      - vim
      - vim-runtime
      - vim-tiny
      - vim-common
      - python
      - python-minimal
      - libpython-dev
      - libpython-stdlib
      - libpython2.7
      - python2.7
      - python2.7-minimal
      - libpython2.7-stdlib
      - libpython2.7-minimal
      - pulseaudio-module-bluetooth
  become: true

- name: Disable bluetooth service
  ansible.builtin.service:
    name: bluetooth.service
    enabled: false
  become: true
