--- # abs_path, without dependencies
- name: Install rsync for sync settings
  apt:
    name: rsync
    state: present
  become: yes

- name: rsyncd.conf
  template: src="{{files_dir}}/respeaker/etc/rsyncd.conf" dest=/etc/rsyncd.conf mode=0644 group=root owner=root
  become: yes

- name: Enable and start rsyncd service for sync settings
  service: name=rsync.service enabled=yes state=started
  become: yes
