--- # abs_path, without dependencies
- name: Install rsync for sync settings
  ansible.builtin.apt:
    name: rsync
    state: present
  become: true

- name: rsyncd.conf
  ansible.builtin.template:
    src: "{{files_dir}}/respeaker/etc/rsyncd.conf"
    dest: /etc/rsyncd.conf
    group: root
    owner: root
    mode: "0644"
  become: true

- name: Enable and start rsyncd service for sync settings
  ansible.builtin.service:
    name: rsync.service
    enabled: true
    state: started
  become: true
