--- # abs_path, rsync.yml, smart_home_install.yml

- name: Synchronization smart-home
  synchronize:
    src: /home/rean/projects/home/smart-home
    dest: /project
    delete: true

- name: Generate protobuf
  shell: /project/smart-home/generate_proto.sh

# ansible-vault decrypt config.py
# ansible-vault encrypt config.py
- name: Copy config.py for smart-home
  copy:
    src: "{{files_dir}}/respeaker/project/smart-home/config.py"
    dest: /project/smart-home/
    decrypt: yes
    owner: rean
    group: users
    mode: 0644
