--- # abs_path, pyenv.yml

- name: Install packages for smart home
  ansible.builtin.apt:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - protobuf-compiler
      - portaudio19-dev
  become: true

- name: Create dirs for smart-home
  ansible.builtin.file:
    path: /project/venv
    state: directory
    group: users
    owner: rean
    mode: "0755"
    recurse: true
  become: true

- name: requirements.txt for smart_home
  ansible.builtin.template:
    src: "{{files_dir}}/respeaker/project/requirements.txt"
    dest: /project/requirements.txt
    group: users
    owner: rean
    mode: "0644"

- name: .python-version for use python3.7
  ansible.builtin.template:
    src: "{{files_dir}}/respeaker/project/.python-version"
    dest: /project/.python-version
    group: users
    owner: rean
    mode: "0644"

- name: Install packages for smart-home
  ansible.builtin.pip:
    requirements: /project/requirements.txt
    chdir: /project/
