--- # abs_path, rsync.yml, smart_home_install.yml

- name: Synchronization smart-home
  ansible.posix.synchronize:
    src: /home/rean/projects/home/smart-home
    dest: /project
    delete: true

- name: Generate protobuf
  ansible.builtin.shell: /project/smart-home/generate_proto.sh

# ansible-vault decrypt config.py
# ansible-vault encrypt config.py
- name: Copy config.py for smart-home
  ansible.builtin.copy:
    src: "{{files_dir}}/respeaker/project/smart-home/config.py"
    dest: /project/smart-home/
    decrypt: true
    group: users
    owner: rean
    mode: "0644"
