--- # abs_path, pyenv.yml

- name: Install packages for smart home
  apt:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - protobuf-compiler
      - portaudio19-dev
  become: yes

- name: Create dirs for smart-home
  file: path=/project/venv state=directory mode=0755 group=users owner=rean recurse=yes
  become: yes

- name: requirements.txt for smart_home
  template: src="{{files_dir}}/respeaker/project/requirements.txt" dest=/project/requirements.txt mode=0644 group=users owner=rean

- name: .python-version for use python3.7
  template: src="{{files_dir}}/respeaker/project/.python-version" dest=/project/.python-version mode=0644 group=users owner=rean

- name: Install packages for smart-home 
  pip:
    requirements: /project/requirements.txt
    chdir: /project/
