--- # without dependencies
- name: Install package refind-efi
  pacman: name=refind-efi state=present
  become: yes

- name: Check that the /boot/efi/EFI exists
  stat: path=/boot/efi/EFI
  register: efi_installed
  become: yes

- name: Find efi partition name
  shell: findmnt -o SOURCE --noheadings /boot/efi
  register: efi_partition_name_reg
  changed_when: false

- name: Find root partition uuid
  shell: findmnt -o UUID --noheadings /
  register: root_partition_uuid_reg
  changed_when: false

- name: Set partitions facts
  set_fact:
    efi_partition_name: "{{ efi_partition_name_reg.stdout }}"
    root_partition_uuid: "{{ root_partition_uuid_reg.stdout }}"

- name: UEFI install
  shell: refind-install --usedefault {{ efi_partition_name }} --alldrivers
  when: efi_installed.stat.exists == False
  become: yes

- name: Copy refind_linux configuration
  template: src=files/boot/refind_linux.conf dest=/boot/refind_linux.conf owner=root group=root mode=0644
  become: yes

- name: Update refind timeout
  lineinfile: regexp='^timeout .*$' line="timeout 1" path=/boot/efi/EFI/BOOT/refind.conf
  become: yes
