---
- name: Install package grub
  pacman: name=grub state=present
  become: yes

- name: Install package efibootmgr
  pacman: name=efibootmgr state=present
  become: yes

- name: Check that the /boot/efi/EFI exists
  stat: path=/boot/efi/EFI
  register: grub_installed
  become: yes

- name: Grub install
  shell: grub-install
  when: grub_installed.stat.exists == False
  become: yes

- name: Update GRUB timeout
  lineinfile: regexp='^GRUB_TIMEOUT=.*$' line="GRUB_TIMEOUT=1" path=/etc/default/grub
  when: grub_installed.stat.exists == False
  become: yes

- name: Grub install
  shell: grub-mkconfig -o /boot/grub/grub.cfg
  when: grub_installed.stat.exists == False
  become: yes
