--- # without dependencies
- name: Get current local user
  run_once: True
  set_fact:
    ansible_local_user: "{{ lookup('pipe', 'id -un') | d(lookup('pipe', 'whoami'), True) | d(lookup('env', 'USER'), True) |  d(lookup('env', 'user'), True) |  d(lookup('env', 'LOGNAME'), True) }}"
  failed_when: ansible_local_user == ''

- name: Find board uuid
  run_once: True
  shell: cat /sys/class/dmi/id/product_uuid | sha256sum | awk '{ print $1 }'
  register: init_board_serial
  changed_when: false
  become: yes
  tags: init

- name: Set archhost hostname
  run_once: True
  set_fact:
    notebook: "no"
    hostname_id: "archhost"
  when: init_board_serial.stdout == '2d4ac2d6ec3acf216141eff067c66c66b0b5c777234763456b4f8a4d219e8043'
  tags: init

- name: Set archmini hostname
  run_once: True
  set_fact:
    notebook: "yes"
    hostname_id: "archmini"
  when: init_board_serial.stdout == '93507fdfe172eea26bfb5bc957a12f41fc36859d2ecfa1131f723d0398dc6868'
  tags: init

- name: Set archsrv hostname
  run_once: True
  set_fact:
    notebook: "no"
    hostname_id: "archsrv"
  when: init_board_serial.stdout == '7053bd838a745311203438c58dcb92661d68b1d55c169f46b58706c1d95c69a9'
  tags: init

- name: Set archnote hostname
  run_once: True
  set_fact:
    notebook: "yes"
    hostname_id: "archnote"
  when: init_board_serial.stdout == '7fdc78b0e186c3f5247f7c20518e9f1ad1903ad95d49fe2d8b7662945741a597'
  tags: init

- name: Set hostname
  hostname: name={{hostname_id}}
  when: ansible_local_user != "root"
  become: yes
