--- # abs_path, without dependencies
- name: Find board uuid
  shell: cat /sys/class/dmi/id/product_name
  register: init_product_name
  changed_when: false
  become: yes
  tags: init

- name: Set archhost hostname
  set_fact:
    notebook: False
    hostname_id: "archhost"
  when: init_product_name.stdout == 'MS-7978'
  tags: init

- name: Set archnote hostname (xiaomi)
  set_fact:
    notebook: True
    hostname_id: "archnote"
  when: init_product_name.stdout == 'TM1613'
  tags: init

- name: Set archsrv hostname
  set_fact:
    notebook: False
    hostname_id: "archsrv"
  when: init_product_name.stdout == 'System Product Name'
  tags: init
