--- # abs_path
- name: Install local mashine

  hosts: local

  vars_files:
    - ../../vars/path.yml
    - ../../vars/common.yml
    - ../../vars/dotfiles_map.yml
    - ../../vars/repository_map.yml

  tasks:
    - include: "{{tasks_dir}}tasks/repository.yml"
    - include: "{{tasks_dir}}tasks/dotfiles.yml"
    - include: "{{tasks_dir}}tasks/lightdm.yml"
    - include: "{{tasks_dir}}tasks/xorg.yml"
    - include: "{{tasks_dir}}tasks/clear.yml"
    - include: "{{tasks_dir}}tasks/monitoring.yml"
    - include: "{{tasks_dir}}tasks/go.yml"
