--- # abs_path
- name: Install local mashine

  hosts: local

  vars_files:
    - ../../vars/common.yml

  tasks:
    - include: "{{tasks_dir}}tasks/xorg.yml"
    - include: "{{tasks_dir}}tasks/clear.yml"
    - include: "{{tasks_dir}}tasks/monitoring.yml"
    - include: "{{tasks_dir}}tasks/go.yml"
