--- # abs_path
- name: Root install local mashine

  hosts: local
  gather_facts: false
  pre_tasks:
    - name: Custom setup
      setup:
        gather_subset:
          - '!all'
          - '!any'

  environment:
    GNUPGHOME: /home/rean/.config/gnupg
  
  vars_files:
    - ../../vars/path.yml
    - ../../vars/common.yml

  tasks:
    - include: "{{tasks_dir}}/common/init.yml"
    - include: "{{tasks_dir}}/common/locale.yml"
    - include: "{{tasks_dir}}/common/user.yml"
    - include: "{{tasks_dir}}/common/pacman.yml"
    - include: "{{tasks_dir}}/common/boot.yml"
