--- # abs_path
- name: Install local mashine

  hosts: local
  gather_facts: false
  pre_tasks:
    - name: Custom setup
      setup:
        gather_subset:
          - '!all'
          - '!any'

  environment:
    GNUPGHOME: /home/rean/.config/gnupg

  vars_files:
    - ../../vars/path.yml
    - ../../vars/common.yml
    - ../../vars/dotfiles_map.yml
    - ../../vars/repository_map.yml

  tasks:
    - include: "{{tasks_dir}}tasks/common/pkgcacheclean.yml"
    - include: "{{tasks_dir}}tasks/common/systemd_cfg.yml"
    - include: "{{tasks_dir}}tasks/common/time.yml"
    # - include: "{{tasks_dir}}tasks/common/autofs.yml"
    - include: "{{tasks_dir}}tasks/packages.yml"
    - include: "{{tasks_dir}}tasks/repository.yml"
    - include: "{{tasks_dir}}tasks/dotfiles.yml"
    - include: "{{tasks_dir}}tasks/lightdm.yml"
    - include: "{{tasks_dir}}tasks/docker.yml"
    - include: "{{tasks_dir}}tasks/xorg.yml"
    - include: "{{tasks_dir}}tasks/clear.yml"
    - include: "{{tasks_dir}}tasks/monitoring.yml"
    - include: "{{tasks_dir}}tasks/go.yml"
