--- # init.yml + not working under root
- name: Set hostname
  hostname: name={{hostname_id}}
  become: yes

- name: Check that wlp1s0-Arch5 service exists
  stat: path="/etc/systemd/system/multi-user.target.wants/netctl@wlp1s0\\x2dArch5.service"
  register: wifi5_service_installed
  become: yes

# ansible-vault encrypt secrets.yml
# ansible-vault decrypt secrets.yml
- name: Copy netctl configuration
  template: src=files/etc/netctl/{{item}} dest=/etc/netctl/{{item}} owner=root group=root mode=0600
  become: yes
  with_items:
    - wlp1s0-Arch5
    - wlp2s0-Arch2

- name: Enable wlp1s0-Arch5
  command: netctl enable wlp1s0-Arch5
  when: wifi5_service_installed.stat.exists == False
  become: yes

- name: Start wlp1s0-Arch5
  command: netctl start wlp1s0-Arch5
  when: wifi5_service_installed.stat.exists == False
  become: yes
