---
- name: Install packages for wifi
  pacman: name={{item}} state=present
  become: yes
  with_items:
    - dialog
    - connman
    - wpa_supplicant

- name: Set hostname
  hostname: name={{hostname_id}}
  when: ansible_local_user != "root"
  become: yes
