--- # user.yml
- name: Create ssh directory
  file: path=/home/{{main_user}}/.ssh state=directory mode=0700 group=users owner={{main_user}}

- name: Copy git config
  copy: src=files/home/.ssh/config dest=~/.ssh/config mode=0400 group=users owner={{main_user}}

# ansible-vault decrypt secrets.yml
# ansible-vault encrypt secrets.yml
- name: Install ssh keys for github
  copy: content="{{ github_private_key }}" dest=/home/{{main_user}}/.ssh/github mode=0400 group=users owner={{main_user}}

- name: Install ssh keys for work
  copy: content="{{ work_private_key }}" dest=/home/{{main_user}}/.ssh/id_rsa mode=0400 group=users owner={{main_user}}

- name: Install ssh keys for vscale
  copy: content="{{ vscale_private_key }}" dest=/home/{{main_user}}/.ssh/vscale mode=0400 group=users owner={{main_user}}

- name: Install ssh keys for hass
  copy: content="{{ hass_private_key }}" dest=/home/{{main_user}}/.ssh/hass mode=0400 group=users owner={{main_user}}
