---
- name: Configure swap for destop
  template: src=files/etc/sysctl.d/99-sysctl.conf.destop dest=/etc/sysctl.d/99-sysctl.conf mode=0644 group=root owner=root
  when: notebook == "no"
  become: yes

- name: Configure swap for notebooks
  template: src=files/etc/sysctl.d/99-sysctl.conf.notebook dest=/etc/sysctl.d/99-sysctl.conf mode=0644 group=root owner=root
  when: notebook == "yes"
  become: yes
