--- # network.yml + packages.yml?
- name: Set timezone to Europe/Moscow
  timezone:
    hwclock: 'UTC'
    name: Europe/Moscow
  become: yes

- name: Check is ntp enabled
  shell: timedatectl | grep "System clock synchronized" | awk '{ print $4 }'
  register: timedatectl_ntp
  changed_when: false

- name: Copy ntp config file
  template: src=files/etc/systemd/timesyncd.conf dest=/etc/systemd/timesyncd.conf mode=0446 group=root owner=root
  become: yes

- name: Enable ntp
  command: timedatectl set-ntp true
  when: timedatectl_ntp.stdout != 'yes'
  become: yes
