---
- name: Check is timezone init
  shell: timedatectl | grep "Time zone" | awk '{ print $3 }'
  register: timedatectl_timezone
  changed_when: false

- name: Check is ntp enabled
  shell: timedatectl | grep "Network time on" | awk '{ print $4 }'
  register: timedatectl_ntp
  changed_when: false

- name: Set time zone
  command: timedatectl set-timezone Europe/Moscow
  when: timedatectl_timezone.stdout != 'Europe/Moscow'
  become: yes

- name: Copy ntp config file
  template: src=files/etc/systemd/timesyncd.conf dest=/etc/systemd/timesyncd.conf mode=0446 group=root owner=root
  become: yes

- name: Enable ntp
  command: timedatectl set-ntp true
  when: timedatectl_ntp.stdout != 'yes'
  become: yes

- name: Hwclock settings
  shell: hwclock --systohc --utc
  when: ansible_local_user != 'root'
  become: yes
