---
- name: Is timezone init
  shell: timedatectl | grep Time | awk '{ print $3 }'
  register: timedatectl_timezone
  changed_when: false

- name: Set time zone
  file: timedatectl set-timezone Europe/Moscow
  when: timedatectl_timezone.stdout != 'Europe/Moscow'
  become: yes
