--- # abs_path, init.yml
- name: Find docker group
  shell: getent group docker
  register: init_docker_group
  changed_when: false
  failed_when: init_docker_group.rc == 1

- name: Set docker group exists
  set_fact:
    docker_group: ",docker"
  when: init_docker_group.rc == 0

- name: Set docker group not exists
  set_fact:
    docker_group: ""
  when: init_docker_group.rc != 0

- name: Create main user
  user: name={{main_user}} uid=1000 group=users groups=games,video,audio,optical,storage,power{{docker_group}} password={{main_password}}
  become: yes

- name: Create dop user
  user: name={{dop_user}} uid=1001 group=users groups=games,video,audio,optical,storage,power password={{dop_password}}
  when: hostname_id == "archnote"
  become: yes

- name: Change root password
  user: name=root password={{main_password}} update_password=always
  become: yes

- name: Configure sudoers
  template: src="{{files_dir}}/etc/sudoers" dest=/etc/sudoers mode=0440 group=root owner=root
  become: yes
