---
- name: Create main user
  user: name={{main_user}} uid=1000 group=users groups=games,video,audio,optical,storage,power{{docker_group}} password={{password}}
  become: yes

- name: Change root password
  user: name=root password={{password}} update_password=always
  become: yes

- name: Configure sudoers
  template: src=files/etc/sudoers dest=/etc/sudoers mode=0440 group=root owner=root
  become: yes
