---
- import_tasks: certbot.yml

- name: Udev rule for Z-Wave stick
  ansible.builtin.copy:
    src: 99-usb-serial.rules
    dest: /etc/udev/rules.d/99-usb-serial.rules
    group: root
    owner: root
    mode: "0644"
  become: true

- name: Turn off "Disco lights"
  shell: echo -e -n "\x01\x08\x00\xF2\x51\x01\x00\x05\x01\x51" > /dev/serial/by-id/usb-0658_0200-if00
  become: true

- name: Create dirs for homeassistant
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    group: users
    owner: rean
    mode: "0755"
  loop:
    - /hass
    - /hass/venv
    - /hass/dotfiles-hass
    - /hass/dotfiles-hass/custom_components/hacs
  become: true

- name: Install homeassistant
  pip:
    name: homeassistant
    virtualenv: /hass/venv
    version: 2021.10.7
    virtualenv_site_packages: true

- name: Install HACS
  ansible.builtin.unarchive:
    creates: /hass/dotfiles-hass/custom_components/hacs/__init__.py
    src: https://github.com/hacs/integration/releases/latest/download/hacs.zip
    dest: /hass/dotfiles-hass/custom_components/hacs
    mode: '0755'
    group: users
    owner: rean
    remote_src: true
  become: true

- name: Create service homeassistant
  ansible.builtin.copy:
    src: hass.service
    dest: /etc/systemd/system/hass.service
    group: root
    owner: root
    mode: "0644"
  become: true

- name: Enable homeassistant service
  ansible.builtin.service:
    name: hass.service
    enabled: true
  become: true
