---
- import_tasks: pkg_arch.yml
  when: distro == "arch" or distro == "archarm"

- import_tasks: pkg_debian.yml
  when: distro == "debian"

- name: All for root user
  community.general.sudoers:
    name: "root-all"
    state: present
    user: "root"
    nopassword: false
    commands: "ALL"
  become: true

- name: Configure sudoers
  ansible.builtin.template:
    src: sudoers
    dest: /etc/sudoers
    group: root
    owner: root
    mode: "0440"
  become: true
