---
- import_tasks: pkg_arch.yml
  when: distro == "arch" or distro == "archarm"

- import_tasks: pkg_debian.yml
  when: distro == "debian"

- name: All for root user
  community.general.sudoers:
    name: "root-all"
    state: present
    user: "root"
    nopassword: false
    commands: "ALL"
  become: true

- name: Nopassword for main user
  community.general.sudoers:
    name: "{{ main_user }}-nopassword"
    state: present
    user: "{{ main_user }}"
    nopassword: true
    commands:
      - /usr/bin/systemctl poweroff
      - /usr/bin/systemctl reboot
      - /usr/bin/systemctl suspend
      - /usr/bin/systemctl hibernate
      - /usr/bin/nvidia-settings *
  become: true

- name: All for main user
  community.general.sudoers:
    name: "{{ main_user }}-all"
    state: present
    user: "{{ main_user }}"
    nopassword: false
    commands: "ALL"
    runas: "ALL"
  become: true

- name: Configure sudoers
  ansible.builtin.template:
    src: sudoers
    dest: /etc/sudoers
    group: root
    owner: root
    mode: "0440"
  become: true
