---
- import_tasks: arch.yml
  when: os_family == "arch"

- import_tasks: debian.yml
  when: os_family == "debian"

- name: All for root user
  community.general.sudoers:
    name: "root-all"
    state: present
    user: "root"
    nopassword: false
    commands: "ALL"
  become: true

- name: Nopassword for main user
  community.general.sudoers:
    name: "{{ main_user }}-nopassword"
    state: present
    user: "{{ main_user }}"
    nopassword: true
    commands:
      - /usr/bin/systemctl poweroff
      - /usr/bin/systemctl reboot
      - /usr/bin/systemctl suspend
      - /usr/bin/systemctl hibernate
  become: true

- name: All for main user
  community.general.sudoers:
    name: "{{ main_user }}-all"
    state: present
    user: "{{ main_user }}"
    nopassword: false
    commands: "ALL"
  become: true

- name: Configure sudoers
  template:
    src: sudoers
    dest: /etc/sudoers
    mode: "0440"
    owner: root
    group: root
  become: true
