---
- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600
  become: true
  changed_when: false

- name: Install sudo package
  ansible.builtin.apt:
    name: sudo
    state: present
  become: true
