---
- name: Install mosquitto package
  pkg_manager:
    name: mosquitto
  become: yes
  become_user: "{{install_user}}"

- name: Enable and start mosquitto service
  service:
    name: mosquitto.service
    enabled: yes
    state: started
  become: yes
