---
- include: kvm_libvirt.yml
  when: virtualization == "kvm_libvirt"

- include: kvm_qemu.yml
  when: virtualization == "kvm_qemu"

- name: Add group user
  user:
    name: "{{ main_user }}"
    append: yes
    groups: libvirt
  become: yes

- name: Set memory limits for libvirt group
  copy:
    src: limits.conf
    dest: /etc/security/limits.conf
    mode: 0644
    group: root
    owner: root
  become: yes

- name: Set permissions for libvirt group
  copy:
    src: 10-libvirt-permissions.rules
    dest: /etc/udev/rules.d/10-libvirt-permissions.rules
    mode: 0644
    group: root
    owner: root
  become: yes
