---

- name: Install specific setup packages
  pkg_manager:
    name: dialog,libnewt
  become: yes
  become_user: "{{install_user}}"

- name: Install packages for wireless
  pkg_manager:
    name: iwd
  become: yes
  become_user: "{{install_user}}"
  when: '"wireless" in network_type.split(",")'
