---

- name: Install specific setup packages
  pkg_manager:
    name: dialog,connman,wpa_supplicant
  become: yes
  become_user: "{{install_user}}"
  when: network_type == "wifi" and is_chroot == True
