---
- name: Install package docker
  pkg_manager:
    name: docker, docker-compose
    command: install
  become: true
  become_user: "{{ install_user }}"

- name: Enable and start docker service
  ansible.builtin.service:
    name: docker.service
    enabled: true
  become: true

- name: Add group user
  ansible.builtin.user:
    name: "{{ main_user }}"
    append: true
    groups: docker
  become: true
