---
- name: Install package docker
  pkg_manager:
    name: docker, docker-compose
  become: true
  become_user: "{{ install_user }}"

- name: Enable and start docker service
  service:
    name: docker.service
    enabled: yes
  become: true

- name: Add group user
  user:
    name: "{{ main_user }}"
    append: yes
    groups: docker
  become: true
