---
- name: Install packages
  pacman: name=python2-pip,python2-yaml state=present
  become: yes

- name: Install python dependensy
  pip: name=docker-compose executable=pip2
  become: yes

- name: Create media directory
  file: path=/home/rean/media state=directory

- name: Create data directories
  file: path={{docker_cfg}}data/{{item}} state=directory
  with_items:
    - proxy
    - dokuwiki
    - sync
    - manage

- name: Create log directories
  file: path={{docker_cfg}}log/{{item}} state=directory
  with_items:
    - proxy
    - cadvisor
    - dokuwiki
    - sync
    - tor

- name: Create backup directories
  file: path=/net/backup/{{item}} state=directory
  with_items:
    - proxy
    - dokuwiki
    - sync

- name: Create compose directories
  file: path={{docker_cfg}}compose/{{item}} state=directory
  with_items:
    - manage
    - base

- name: Create compose files
  copy: src=files/archsrv/docker-{{item}}-compose.yml dest={{docker_cfg}}compose/{{item}}/docker-compose.yml
  with_items:
    - manage
    - base

- name: Stop and remove base containers
  docker_service: project_src={{docker_cfg}}compose/base state=absent

- name: Run base containers
  docker_service: project_src={{docker_cfg}}compose/base state=present pull=yes

- name: Run manage container
  docker_service: project_src={{docker_cfg}}compose/manage state=present

- name: Remove old images
  command: docker image prune --force
