---
# ansible-vault decrypt secrets.yaml
# ansible-vault encrypt secrets.yaml
- name: Copy secrets.yaml for hass
  ansible.builtin.copy:
    src: secrets.yaml
    dest: /hass/dotfiles-hass
    decrypt: true
    group: users
    owner: "{{ main_user }}"
    mode: "0644"

- name: Synchronization smart-home
  ansible.posix.synchronize:
    src: /home/{{ main_user }}/projects/home/smart-home
    dest: /hass
    delete: true

- name: Synchronization dotfiles-hass
  ansible.posix.synchronize:
    src: /home/{{ main_user }}/projects/home/dotfiles-hass
    dest: /hass

- name: Generate protobuf
  ansible.builtin.command: /hass/smart-home/generate_proto.sh

- name: Restart homeassistant service
  ansible.builtin.service:
    name: hass.service
    state: restarted
  become: true
