---
- name: Install packages for hddtemp
  pkg_manager:
    name: hddtemp, smartmontools
  become: yes
  become_user: "{{install_user}}"

- name: Create hddtemp service directory
  file:
    path: /etc/systemd/system/hddtemp.service.d
    state: directory
    mode: 0755
    group: root
    owner: root
  become: yes

- name: Remove old hddtemp settings file
  file:
    path: /tmp/customexec.conf
    state: absent
  become: yes
  changed_when: false

- name: Create hddtemp settings file
  script: generate.sh > /tmp/customexec.conf
  become: yes
  changed_when: false

- name: Install hddtemp settings file
  copy:
    src: /tmp/customexec.conf
    dest: /etc/systemd/system/hddtemp.service.d/customexec.conf
    mode: 0644
    group: root
    owner: root
    remote_src: yes
  become: yes
  register: reg_settings

- name: Remove new hddtemp settings file
  file:
    path: /tmp/customexec.conf
    state: absent
  become: yes
  changed_when: false

- name: Enable and start hddtemp service
  service:
    name: hddtemp.service
    enabled: yes
    state: started
  become: yes

- name: Restart hddtemp service if config changed
  service:
    name: hddtemp.service
    enabled: yes
    state: restarted
  when: reg_settings.changed
  become: yes
