---
- import_tasks: pkg_arch.yml
  when: distro == "arch"

- import_tasks: pkg_archarm.yml
  when: distro == "archarm"

- import_tasks: pkg_debian.yml
  when: distro == "debian"

# ansible-vault decrypt 0_config.json
# ansible-vault encrypt 0_config.json
- name: Copy sing box config files
  ansible.builtin.copy:
    src: 0_config.json
    dest: /etc/sing-box/0_config.json
    decrypt: true
    owner: root
    group: root
    mode: "0644"
  become: true

- name: Enable and restart sing box service
  ansible.builtin.service:
    name: sing-box.service
    enabled: true
    daemon_reload: true
    state: restarted
  become: true
