---
- import_tasks: pkg_arch.yml
  when: distro == "arch"

- import_tasks: pkg_archarm.yml
  when: distro == "archarm"

- import_tasks: pkg_debian.yml
  when: distro == "debian"

# ansible-vault decrypt main_cfg.json
# ansible-vault encrypt main_cfg.json
- name: Copy sing box config files
  ansible.builtin.copy:
    src: main_cfg.json
    dest: /etc/sing-box/main_cfg.json
    decrypt: yes
    owner: root
    group: root
    mode: 0644
  become: true

- name: Enable and restart sing box service
  ansible.builtin.service:
    name: sing-box.service
    enabled: true
    daemon_reload: true
    state: restarted
  become: true
