---
- name: Copy arch pacman configuration
  copy:
    src: arch_pacman.conf
    dest: /etc/pacman.conf
    mode: 0644
    owner: root
    group: root
  become: yes

- name: Copy arch mirrorlist configuration
  copy:
    src: arch_mirrorlist
    dest: /etc/pacman.d/mirrorlist
    mode: 0644
    owner: root
    group: root
  become: yes

- name: Update pacman cache
  pacman:
    force: yes
    update_cache: yes
  become: yes
  changed_when: false

- name: install yay
  pkg_manager:
    name: yay
  become: yes
  become_user: "{{ install_user }}"
