---

- include: arch.yml
  when: distro == "arch"

- include: archarm.yml
  when: distro == "archarm"

- include: manjaro.yml
  when: distro == "manjaro"

- name: Update pacman cache
  pacman:
    force: yes
    update_cache: yes
  become: yes
  changed_when: false

- name: install yay
  pkg_manager:
    name: yay
  become: yes
  become_user: "{{install_user}}"
  when: x86_64
