---
- name: Copy pacman configuration
  copy:
    src: "{% if x86_64 %}pacman.conf{% else %}pacman_arm.conf{% endif %}"
    dest: /etc/pacman.conf
    mode: 0644
    owner: root
    group: root
  become: yes

- name: Update pacman cache
  pacman:
    force: yes
    update_cache: yes
  become: yes
  changed_when: false

- name: install yay
  pkg_manager:
    name: yay
  when: x86_64

- name: Install base packages for wifi
  pkg_manager:
    name: dialog,connman,wpa_supplicant
  when: network_type == "wifi"
