---
- name: Copy pacman configuration
  copy:
    src=pacman.conf
    dest=/etc/pacman.conf
    mode=0644
    owner=root
    group=root
  become: yes

- name: Update pacman cache
  pacman:
    force: yes
    update_cache: yes
  become: yes
  changed_when: false

- name: install yay
  pkg_manager:
    name: yay

- name: Install base packages for wifi
  pkg_manager:
    name: dialog,connman,wpa_supplicant
  when: network_type == "wifi"
