version: '2'
services:
  proxy:
    restart: unless-stopped
    container_name: proxy
    hostname: proxy
    image: reangd/alpine-proxy:latest
    environment:
      #
      # base params:
      #
      - S6_LOGGING=1
      # - SERVICE_CRON=0
      # - RESTORE_NAME=daily.0
      # - NGINX_OPTIONS=...
      #
      # proxy params:
      #
      - CERT_EMAIL=reangd@yandex.ru
      - CERT_DOMAIN=reangd.fr.to
      - CERT_PRODACTION=1
      # - CONSUL_PORT=8500
    ports:
      - "80:80"      # HTTP
      - "443:443"    # HTTPS
    networks:
      base:
        ipv4_address: 10.10.0.2
    volumes:
      - /home/rean/docker/log/proxy:/var/log:rw
      - /net/backup/proxy:/backup:rw
      - /home/rean/docker/data/proxy:/data:rw
      - /etc/localtime:/etc/localtime:ro
  cadvisor:
    restart: unless-stopped
    container_name: cadvisor
    hostname: cadvisor
    image: reangd/alpine-cadvisor:latest
    environment:
      #
      # base params:
      #
      - S6_LOGGING=1
      - SERVICE_CRON=0
      #
      # cadvisor params:
      #
      - CADVISOR_OPTIONS=-log_dir /var/log/
    ports:
      - "8080:8080"      # HTTP
    networks:
      base:
        ipv4_address: 10.10.0.3
    volumes:
      - /home/rean/docker/log/cadvisor:/var/log:rw
      - /etc/localtime:/etc/localtime:ro
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /home/rean/docker/cache:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
  dokuwiki:
    restart: unless-stopped
    container_name: dokuwiki
    hostname: dokuwiki
    image: reangd/alpine-dokuwiki:latest
    environment:
      #
      # base params:
      #
      - S6_LOGGING=1
      # - SERVICE_CRON=1
      # - RESTORE_NAME=daily.0
      # - NGINX_OPTIONS=...
    # ports:
    #   - "80:80"      # HTTP
    networks:
      base:
        ipv4_address: 10.10.0.10
    volumes:
      - /home/rean/docker/log/dokuwiki:/var/log:rw
      - /net/backup/dokuwiki:/backup:rw
      - /home/rean/docker/data/dokuwiki:/data:rw
      - /etc/localtime:/etc/localtime:ro
  jenkins:
    restart: unless-stopped
    container_name: jenkins
    hostname: jenkins
    image: reangd/alpine-jenkins:latest
    environment:
      #
      # base params:
      #
      - S6_LOGGING=1
      # - SERVICE_CRON=1
      # - RESTORE_NAME=daily.0
      #
      # jenkins params:
      #
      # - JAVA_OPTS=...
      # - JENKINS_OPTS=...
    # ports:
      # - "80:8080"      # HTTP
    networks:
      base:
        ipv4_address: 10.10.0.11
    volumes:
      - /home/rean/docker/log/jenkins:/var/log:rw
      - /net/backup/jenkins:/backup:rw
      - /home/rean/docker/data/jenkins:/data:rw
      - /etc/localtime:/etc/localtime:ro
  tor:
    restart: unless-stopped
    container_name: tor
    hostname: tor
    image: reangd/alpine-tor:latest
    environment:
      #
      # base params:
      #
      - S6_LOGGING=1
      - SERVICE_CRON=0
    ports:
      - "9050:9050"
    networks:
      base:
        ipv4_address: 10.10.0.12
    volumes:
      - /home/rean/docker/log/tor:/var/log:rw
      - /etc/localtime:/etc/localtime:ro
networks:
  base:
    driver: bridge
    ipam:
      config:
        - subnet: 10.10.0.0/16
          gateway: 10.10.0.1
    driver_opts:
      com.docker.network.bridge.host_binding_ipv4: "192.168.1.100"
