version: '2'
services:
  proxy:
    restart: unless-stopped
    container_name: proxy
    hostname: proxy
    image: reangd/alpine-proxy:latest
    environment:
      - S6_LOGGING=1
      - SERVICE_CRON=1
      - CERT_EMAIL=reangd@yandex.ru
      - CERT_DOMAIN=reangd.fr.to
      - CERT_PRODACTION=1
    ports:
      - "80:80"
      - "443:443"
    networks:
      base:
        ipv4_address: 10.10.0.2
    volumes:
      - /home/rean/docker/log/proxy:/var/log:rw
      - /net/backup/proxy:/backup:rw
      - /home/rean/docker/data/proxy:/data:rw
      - /etc/localtime:/etc/localtime:ro
  cadvisor:
    restart: unless-stopped
    container_name: cadvisor
    hostname: cadvisor
    image: reangd/alpine-cadvisor:latest
    environment:
      - S6_LOGGING=1
      - SERVICE_CRON=0
      - CADVISOR_OPTIONS=-log_dir /var/log/
    networks:
      base:
        ipv4_address: 10.10.0.3
    volumes:
      - /home/rean/docker/log/cadvisor:/var/log:rw
      - /etc/localtime:/etc/localtime:ro
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /home/rean/docker/cache:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
  dokuwiki:
    restart: unless-stopped
    container_name: dokuwiki
    hostname: dokuwiki
    image: reangd/alpine-dokuwiki:latest
    environment:
      - S6_LOGGING=1
      - SERVICE_CRON=1
    networks:
      base:
        ipv4_address: 10.10.0.10
    volumes:
      - /home/rean/docker/log/dokuwiki:/var/log:rw
      - /net/backup/dokuwiki:/backup:rw
      - /home/rean/docker/data/dokuwiki:/data:rw
      - /etc/localtime:/etc/localtime:ro
  sync:
    restart: unless-stopped
    container_name: sync
    hostname: sync
    image: reangd/alpine-sync:latest
    environment:
      - S6_LOGGING=1
      - SERVICE_CRON=1
    networks:
      base:
        ipv4_address: 10.10.0.11
    volumes:
      - /home/rean/docker/log/sync:/var/log:rw
      - /net/backup/sync:/backup:rw
      - /home/rean/docker/data/sync:/data:rw
      - /home/rean/media:/storage:rw
      - /etc/localtime:/etc/localtime:ro
  tor:
    restart: unless-stopped
    container_name: tor
    hostname: tor
    image: reangd/alpine-tor:latest
    environment:
      - S6_LOGGING=1
      - SERVICE_CRON=0
    ports:
      - "9050:9050"
    networks:
      base:
        ipv4_address: 10.10.0.12
    volumes:
      - /home/rean/docker/log/tor:/var/log:rw
      - /etc/localtime:/etc/localtime:ro
networks:
  base:
    driver: bridge
    ipam:
      config:
        - subnet: 10.10.0.0/16
          gateway: 10.10.0.1
    driver_opts:
      com.docker.network.bridge.host_binding_ipv4: "192.168.1.100"
