---
- name: Add helm repositories
  kubernetes.core.helm_repository:
    name: "{{ item.name }}"
    repo_url: "{{ item.url }}"
  loop:
    - {name: "twuni",       url: "https://helm.twun.io" }
    - {name: "jetstack",    url: "https://charts.jetstack.io" }
    - {name: "traefik",     url: "https://helm.traefik.io/traefik" }
    - {name: "k8s-at-home", url: "https://k8s-at-home.com/charts/" }
    - {name: "volker",      url: "https://charts.cryptic.systems/volker.raschek" }
