---
- name: Install cert_manager
  kubernetes.core.helm:
    name: cert-manager
    chart_version: v1.6.1
    chart_ref: jetstack/cert-manager
    release_namespace: web
    create_namespace: true
    values: "{{ lookup('template', 'cert_manager_values.yml') | from_yaml }}"

- name: Install certificates
  kubernetes.core.k8s:
    definition: "{{ lookup('template', 'certificates.yml') | from_yaml_all | list }}"
