---
- import_tasks: package.yml
  vars:
  - name: drone
  - version: 0.2.4
  - repo: volker/drone
  - namespace: ci
  - extra_template: drone_extra.yml
  - values_template: drone_values.yml
  - volumes:
    - { name: "drone", path: "/drone", size: "20Gi" }
