---
- import_tasks: package.yml
  vars:
  - name: homer
  - version: 7.0.0
  - repo: k8s-at-home/homer
  - namespace: app
  - values_template: homer_values.yml
  - volumes:
    - { name: "homer", path: "/homer", size: "1Gi" }
