---
- import_tasks: helm_plugins.yml
- import_tasks: add_repositories.yml
- import_tasks: traefik.yml
# - import_tasks: traefik_remove.yml
- import_tasks: traefik_forward_auth.yml
# - import_tasks: traefik_forward_auth_remove.yml
