---
# ansible-vault decrypt k8s_vars.yml
# ansible-vault encrypt k8s_vars.yml
- name: Include k8s_vars
  include_vars:
    file: k8s_vars.yml

- import_tasks: helm_plugins.yml
- import_tasks: add_namespaces.yml
- import_tasks: add_repositories.yml
- import_tasks: traefik.yml
# - import_tasks: traefik_remove.yml
- import_tasks: cert_manager.yml
# - import_tasks: cert_manager_remove.yml
- import_tasks: traefik_forward_auth.yml
# - import_tasks: traefik_forward_auth_remove.yml
- import_tasks: homer.yml
# - import_tasks: homer_remove.yml
