---
# ansible-vault decrypt oauth_values.yml
# ansible-vault encrypt oauth_values.yml
- import_tasks: package.yml
  vars:
  - name: oauth
  - version: 1.0.10
  - repo: k8s-at-home/traefik-forward-auth
  - namespace: web
  - values_template: oauth_values.yml
