---
- import_tasks: package.yml
  vars:
  - name: registry
  - version: 2.0.0
  - repo: twuni/docker-registry
  - namespace: app
  - values_template: registry_values.yml
  - volumes:
    - { name: "registry", path: "/registry", size: "20Gi" }
