---
# ansible-vault decrypt traefik_forward_auth_values.yml
# ansible-vault encrypt traefik_forward_auth_values.yml
- name: Include vars passwords
  include_vars:
    file: traefik_forward_auth_values.yml
    name: traefik_forward_auth_values

- name: Install traefik forward auth
  kubernetes.core.helm:
    name: traefik-forward-auth
    chart_version: 1.0.10
    chart_ref: k8s-at-home/traefik-forward-auth
    release_namespace: web
    create_namespace: true
    values: "{{ traefik_forward_auth_values | from_yaml }}"
