---
# ansible-vault decrypt traefik_values.yml
# ansible-vault encrypt traefik_values.yml
- import_tasks: package.yml
  vars:
  - name: traefik
  - version: 10.9.1
  - repo: traefik/traefik
  - namespace: web
  - update_repo: True
  - extra_template: traefik_extra.yml
  - values_template: traefik_values.yml
