--- # abs_path, without dependencies

- name: Install packages for install homeassistant
  pacman: name=python-virtualenv,libffi,protobuf,python-pip,gcc,make,pkg-config,libudev0-shim,mosquitto state=present
  become: yes

- name: Udev rule for Z-Wave stick
  template: src="{{files_dir}}/hass/etc/udev/rules.d/99-usb-serial.rules" dest=/etc/udev/rules.d/99-usb-serial.rules mode=644 group=root owner=root
  become: yes

- name: Create dirs for homeassistant
  file: path={{item}} state=directory mode=0755 group=users owner=rean recurse=yes
  with_items:
    - /hass/venv
    - /hass/dotfiles-hass
  become: yes

- name: Install homeassistant
  pip: 
    name: homeassistant
    virtualenv: /hass/venv
    virtualenv_site_packages: yes

- name: Enable port 80 for hass
  capabilities:
    path: /hass/venv/bin/python
    capability: cap_net_bind_service=+ep
    state: present
  become: yes

- name: Create service homeassistant
  template: src="{{files_dir}}/hass/etc/systemd/hass.service" dest=/etc/systemd/system/hass.service mode=0644 group=root owner=root
  become: yes

- name: Enable homeassistant service
  service: name=hass.service enabled=yes
  become: yes

- name: Enable and start mosquitto service
  service: name=mosquitto.service enabled=yes state=started
  become: yes
