---
- name: Base install home assistant

  hosts: hass

  vars_files:
    - ../../vars/path.yml

  tasks:
    - include: "{{tasks_dir}}/common/locale.yml"
    - include: "{{tasks_dir}}/common/time.yml"
    - include: "{{tasks_dir}}/common/systemd_cfg.yml"
    - include: "{{tasks_dir}}/hass/user.yml"
    - include: "{{tasks_dir}}/hass/hass_install.yml"
    - include: "{{tasks_dir}}/hass/hass_update.yml"