--- # abs_path, without dependencies

- name: Install rsync package
  pacman: name=rsync state=present
  become: yes

- name: Enable and start rsyncd service for sync settings
  service: name=rsyncd.service enabled=yes state=started
  become: yes
